### ISSUE TITLE
Add "FLAC" package

### ISSUE THREAD

**Issue by drodin** [cpp-pm/hunter#119]
* I'm interested in package `FLAC`
* Here is the official site of package https://xiph.org/flac/

* This package is using [Git]: https://github.com/xiph/flac

* Official GitHub repository: https://github.com/xiph/flac

* Used build system: [CMake]

* This package has next dependencies:

  * `libogg` (optional, available in Hunter: https://cpp-pm-hunter.readthedocs.io/en/latest/packages/pkg/libogg.html)

---

**Comment by rbsheth** [comment]
Closed by #116
