### ISSUE TITLE
Version says 0.19 in hunter docs

### ISSUE THREAD

**Issue by hjmallon** [cpp-pm/hunter#124]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://hunter.readthedocs.io/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://hunter.readthedocs.io/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

The hunter docs say version 0.19 (e.g. in titlebar) see [here](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html). 

The value is defined in docs/conf.py. Is there any way to get it to pick the version from the git tag or something?

**Comment by rbsheth** [comment]
Auto-updating the version would be nice - maybe another task for Actions.
