### ISSUE TITLE
(docs.)hunter.sh not available

### ISSUE THREAD

**Issue by kaihowl** [cpp-pm/hunter#125]
I cannot reach `docs.hunter.sh` or `hunter.sh` anymore. This is not isolated to my machine or internet connection.

https://downforeveryoneorjustme.com/hunter.sh

**Comment by rbsheth** [comment]
Yeah, that was a domain for the docs for https://github.com/ruslo/hunter and we didn't have write access. Seems like he took that down, which makes things a bit clearer. You should be using https://hunter.readthedocs.io for the most up-to-date documentation.

**Comment by kaihowl** [comment]
Thank you for the clarification. I just searched for something with DuckDuckGo and this was the first result. 

But this will probably fix itself soon. 

Feel free to close this ticket then.
