### ISSUE TITLE
Add "OpenEXR" package

### ISSUE THREAD

**Issue by hjmallon** [cpp-pm/hunter#128]
* I'm interested in package `OpenEXR`
* Here is the official site of package https://www.openexr.com/
* This package is using [Git]: https://github.com/AcademySoftwareFoundation/openexr
* Used build system: [CMake]

* This package has next dependencies:
  * `IlmBase` (part of openexr download)
  * `ZLIB` In hunter

Here is the package request from old hunter https://github.com/ruslo/hunter/issues/361

---

I have already got this working in a test branch (thanks to the great work done upstream in improving their CMake build system recently). I have 3 PRs open upstream taken from my hunterize-2 branch.

* https://github.com/AcademySoftwareFoundation/openexr/pull/634
* https://github.com/AcademySoftwareFoundation/openexr/pull/635
* https://github.com/AcademySoftwareFoundation/openexr/pull/639

I will need a fork in hunter-packages to add the `hunter_add_package` and `HunterGate` on top of those commits (which hopefully will be absorbed upstream).

**Comment by rbsheth** [comment]
@hjmallon Thanks for getting some PRs upstream! I made a fork here: https://github.com/cpp-pm/openexr

**Comment by hjmallon** [comment]
https://github.com/cpp-pm/openexr/pull/1

Added hunterization PR to that fork.

**Comment by hjmallon** [comment]
Note to self, tasks required:

- [ ] Merge hunterisation here 2.4.0-p0 https://github.com/cpp-pm/openexr/pull/1
- [ ] Make PR based on that. `pr.IlmBase` for IlmBase
- [ ] Wait for release with IlmBase
- [ ] Add testing PR for IlmBase
- [ ] Make v2.4.0-p1 with a Hunter release including IlmBase
- [ ] Make PR based on that `pr.OpenEXR` which also includes pointing IlmBase at version 2.4.0-p1
- [ ] Wait for release with OpenEXR and IlmBase
- [ ] Add testing PR for OpenEXR

Adding packages with 2 dependant packages inside them is a little complicated as the hunterisation of a package includes a link to a version of hunter that itself supports building part of the package...

**Comment by rbsheth** [comment]
@hjmallon It would be nice to split `IlmBase` out but that will be a nightmare to maintain, so I'm okay with your proposed steps.

**Comment by hjmallon** [comment]
> @hjmallon It would be nice to split `IlmBase` out but that will be a nightmare to maintain, so I'm okay with your proposed steps.

Quote from @cary-ilm

> Our intention with the 3.0 release later in the year is to split these projects into separate github repos, creating proper dependencies between them, which will mean an entire re-vamp of the cmake setup.

As mentioned here https://github.com/AcademySoftwareFoundation/openexr/pull/639 the OpenEXR are planning to split IlmBase and OpenEXR in a v3.0.0 release this year anyway. So the weird dependency will be sorted then.

**Comment by rbsheth** [comment]
@hjmallon Closing as #138 and #164 have been merged
