### ISSUE TITLE
hunter_venv changes CMAKE_FIND_FRAMEWORK unnecessarily 

### ISSUE THREAD

**Issue by hjmallon** [cpp-pm/hunter#130]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://hunter.readthedocs.io/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://hunter.readthedocs.io/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.15)

include("cmake/HunterGate.cmake")
HunterGate(
    URL "..."
    SHA1 "..."
)

project(foo)

hunter_add_package(hunter_venv)
find_package(hunter_venv CONFIG REQUIRED)

# Fails as CMAKE_FIND_FRAMEWORK set to NEVER
find_library(ACCEL Accelerate)
```

* I'm building on [OSX].
* [I'm using official CMake release]
* CMake version: <3.16.2>

---

Since cmake 3.15 a new option has been available `Python_FIND_VIRTUALENV`, which avoids the need to change the macOS global CMake setting `CMAKE_FIND_FRAMEWORK` and the Windows `Python_FIND_REGISTRY` (which is at least Python specific so probably OK).

I will need a hunter-packages for `hunter_venv` to make an update to it something like the following:

```cmake
if (version is >= 3.15)
  set(Python_FIND_VIRTUALENV ONLY)
else()
  set(CMAKE_FIND_FRAMEWORK NEVER)
  set(Python_FIND_REGISTRY NEVER)
endif()
```

**Comment by bkotzz** [comment]
https://github.com/cpp-pm/hunter_venv/releases/tag/v1.0.2
