### ISSUE TITLE
PRs are not double checked before merge

### ISSUE THREAD

**Issue by caseymcc** [cpp-pm/hunter#152]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://hunter.readthedocs.io/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://hunter.readthedocs.io/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

PRs are not being double checked before merging. I am not sure how Ruslo did it but all the PRs before were checked by the hunter repo travis/appveyor instance (rather the just the PR author) before being merged.

**Comment by NeroBurner** [comment]
he did it by hand, picking the PRs branch and pushing to the deep-pkg-testing repo

**Comment by rbsheth** [comment]
Yeah, I've been relying on the PR authors for now. 😬

**Comment by rbsheth** [comment]
I think this is solved with #250 now, since CI and hunter's main repo are merged together. Every PR will have its toolchain set run automatically.
