### ISSUE TITLE
Add "SPIRV-Tools" package

### ISSUE THREAD

**Issue by mchiasson** [cpp-pm/hunter#16]
* I'm interested in package `SPIRV-Tools`
* Here is the official site of package https://github.com/KhronosGroup/SPIRV-Tools

* This package is using Git: https://github.com/KhronosGroup/SPIRV-Tools

* Official GitHub repository: https://github.com/KhronosGroup/SPIRV-Tools

* Used build system: CMake

* Unofficial CMake support: https://github.com/mchiasson/SPIRV-Tools

* This package has next dependencies:

  * `SPIRV-Headers` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/SPIRV-Headers.html)

---

**Comment by mchiasson** [comment]
@bkotzz @rbsheth For new packages, are you guys able to create repositories under https://github.com/hunter-packages or do we still need @ruslo's help for this?

btw, I've already done the hunterization work for SPIRV-Tools. I just need a place to share it ;-)

**Comment by mchiasson** [comment]
oh i see.

https://github.com/cpp-pm/hunter/issues/12#issuecomment-535315673

it's all going to go under the `cpp-pm` umbrella. Very good!

**Comment by bkotzz** [comment]
Yep, we have no access to the old github org, so everything is coming under the cpp-pm umbrella now. I can create a fork for you here

**Comment by bkotzz** [comment]
https://github.com/cpp-pm/SPIRV-Tools

**Comment by mchiasson** [comment]
Perfect. Thank you. It won't take too long. ;-)

**Comment by mchiasson** [comment]
@bkotzz I have a small favor to ask you: can you go on https://github.com/cpp-pm/SPIRV-Tools and create a `hunter` branch based off this https://github.com/cpp-pm/SPIRV-Tools/tree/v2019.4 release tag? For every hunter packages I contributed, I always avoid using the latest WIP on the master branch because it can be unstable.

**Comment by bkotzz** [comment]
Sounds good. Here you go https://github.com/cpp-pm/SPIRV-Tools/tree/hunter

**Comment by mchiasson** [comment]
@bkotzz you are awesome. Thanks

**Comment by mchiasson** [comment]
Sorry, it looks like my `SPIRV-Headers` contribution hasn't been released yet on https://github.com/cpp-pm/hunter/releases. I guess I will have to wait for the next release before I can do this package.

**Comment by bkotzz** [comment]
That’s my fault - I can get a release for you today. In the future I would like to have every commit automatically create a release and take the human out of the process :)

**Comment by rbsheth** [comment]
@mchiasson https://github.com/cpp-pm/hunter/releases/tag/v0.23.217

**Comment by mchiasson** [comment]
yup. got it. thank you :)

**Comment by mchiasson** [comment]
and the deed is done: https://github.com/cpp-pm/SPIRV-Tools/pull/1
