### ISSUE TITLE
spdlog release 1.5.0 available

### ISSUE THREAD

**Issue by NeroBurner** [cpp-pm/hunter#163]
spdlog 1.5.0 was released and available

https://github.com/gabime/spdlog/releases/tag/v1.5.0

**Comment by NeroBurner** [comment]
I've created a `hunter-v1.5.0` branch and a `v1.5.0-p0` tag

could someone push the branches to https://github.com/cpp-pm/spdlog or give me access to the repository?

**Comment by rbsheth** [comment]
@NeroBurner Since you joined `cpp-pm-packages`, you have access to that repo.

**Comment by rbsheth** [comment]
@NeroBurner Still want to update? I didn't see a PR in that repo

**Comment by rbsheth** [comment]
#260 Updated spdlog to 1.8.0, hopefully that is good enough.
