### ISSUE TITLE
Request for boost package with new Xcode SDK fixes

### ISSUE THREAD

**Issue by YuryAlkevich** [cpp-pm/hunter#178]
After updating Xcode SDK to 11.0.3 version boost now fails to compile because of a bug in boost configuration file
Here is a reported issue in boost git repo
https://github.com/boostorg/build/issues/440
The fix can be applied without boost version update, because it's quite simple. But it's very necessary to apply it

**Comment by DmitrySmolyakov** [comment]
I have the same issue

**Comment by rbsheth** [comment]
I ran into this too recently, we'll need to apply the fix.

**Comment by rbsheth** [comment]
@YuryAlkevich @DmitrySmolyakov Once I get confirmation that the new version works, I will update the default version. Will be running tests on my side as well, need to upgrade to Xcode 11.4.
