### ISSUE TITLE
Hunterized pugixml repository gone

### ISSUE THREAD

**Issue by jothepro** [cpp-pm/hunter#190]
The hunterized pugixml repository (which should be [here](https://github.com/rusdevops/pugixml)) is gone, which is why hunter cannot download the pugixml sources.

Does anyone have insights why the repository was removed? As I still do have a local copy of the hunterized version I could simply publish it myself as a quick fix. (Not sure if that is the best option since I have little experience as a project maintainer and no idea what is going on in this specific fork)

* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://hunter.readthedocs.io/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://hunter.readthedocs.io/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

* I've created [SSCCE](http://www.sscce.org/) reproducing the issue:
```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.2)

include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/cpp-pm/hunter/archive/v0.23.253.tar.gz"
    SHA1 "88ea6d37c897a81a080eb9ae0f69d7807bbb3c73"
)

project(foo)

hunter_add_package(pugixml)
find_package(pugixml CONFIG REQUIRED)
```

Here is the log until first error reported by Hunter, ~~option `HUNTER_STATUS_DEBUG` is `ON`:~~
```
-- [hunter] Building pugixml
 loading initial cache file /builds/jothepro/libcloudsync/.hunter/_Base/88ea6d3/910c339/cc4bc48/cache.cmake
 loading initial cache file /builds/jothepro/libcloudsync/.hunter/_Base/88ea6d3/910c339/cc4bc48/Build/pugixml/args.cmake
 -- The C compiler identification is GNU 9.2.0
 -- The CXX compiler identification is GNU 9.2.0
 -- Check for working C compiler: /usr/bin/cc
 -- Check for working C compiler: /usr/bin/cc -- works
 -- Detecting C compile features
 -- Detecting C compile features - done
 -- Check for working CXX compiler: /usr/bin/c++
 -- Check for working CXX compiler: /usr/bin/c++ -- works
 -- Detecting CXX compile features
 -- Detecting CXX compile features - done
 -- Configuring done
 -- Generating done
 -- Build files have been written to: /builds/jothepro/libcloudsync/.hunter/_Base/88ea6d3/910c339/cc4bc48/Build/pugixml/Build
 Scanning dependencies of target pugixml-Release
 [  6%] Creating directories for 'pugixml-Release'
 [ 12%] Performing download step (download, verify and extract) for 'pugixml-Release'
 -- Downloading...
    dst='/builds/jothepro/libcloudsync/.hunter/_Base/Download/pugixml/1.8.1/005b1c8/v1.8.1-hunter.tar.gz'
    timeout='none'
 -- Using src='https://github.com/rusdevops/pugixml/archive/v1.8.1-hunter.tar.gz'
 -- Retrying...
 -- Using src='https://github.com/rusdevops/pugixml/archive/v1.8.1-hunter.tar.gz'
 -- Retry after 5 seconds (attempt #2) ...
 -- Using src='https://github.com/rusdevops/pugixml/archive/v1.8.1-hunter.tar.gz'
 -- Retry after 5 seconds (attempt #3) ...
 -- Using src='https://github.com/rusdevops/pugixml/archive/v1.8.1-hunter.tar.gz'
 -- Retry after 15 seconds (attempt #4) ...
 -- Using src='https://github.com/rusdevops/pugixml/archive/v1.8.1-hunter.tar.gz'
 -- Retry after 60 seconds (attempt #5) ...
 -- Using src='https://github.com/rusdevops/pugixml/archive/v1.8.1-hunter.tar.gz'
 CMake Error at Build/pugixml-Release-prefix/src/pugixml-Release-stamp/download-pugixml-Release.cmake:159 (message):
   Each download failed!
     error: downloading 'https://github.com/rusdevops/pugixml/archive/v1.8.1-hunter.tar.gz' failed
          status_code: 22
          status_string: "HTTP response code said error"
```

I've checked that the first error in logs **IS NOT** `external.build.failed`. **[Yes]**

---

**Comment by jothepro** [comment]
> Does anyone have insights why the repository was removed?

I guess I can answer this myself, the github user `rusdevops` is gone. :worried:

**Comment by rbsheth** [comment]
@jothepro Ugh, that's annoying. Should I re-fork pugixml into cpp-pm so that you can push the hunterized branches?

**Comment by jothepro** [comment]
That would be great. 👍 I can contribute the original hunterized version, but I'd need some assistance on how to re-integrate it into hunter. I guess some kind of pipeline will be needed to generate a release that can then be linked in hunter?

**Comment by rbsheth** [comment]
Yeah, I usually create the release myself but you can also based on the Hunter branch. We just need to name it correctly.

I created a fork here: https://github.com/cpp-pm/pugixml and added you to cpp-pm-packages. Once you accept the invite you should be able to push the Hunter branches and I can re-create the releases.

**Comment by jothepro** [comment]
I pushed two versions:
1. https://github.com/cpp-pm/pugixml/tree/hunterized the current fork with just the custom cmake from the hunterized version. I guess we should be fine with that (And get a newer version of pugixml, wohoo!).
2. https://github.com/cpp-pm/pugixml/tree/hunterized_original the original version that was distributed with hunter and that I had as a local copy. It is obviously an older version of pugixml.  This is just for reference to do a compare on what has changed since then. I could not find any major changes that might break the build with the hunterized cmake.

If I understood you correctly you will do the rest of the work? I'd appreciate it if you told me what you did so I can better understand how the integration into hunter works :)

**Comment by jothepro** [comment]
Ok I'm confused now. I realized that it would be smarter to hunterize the last release (v.1.10) instead of the masters head. I tried branching of the 1.10 release tag and this somehow [created a branch](https://github.com/cpp-pm/pugixml/tree/hunterized_1_10) that I am not allowed to push to.
I also figured out that [here](https://github.com/cpp-pm/pugixml/blob/hunterized/CMakeLists.txt#L50) the version needs to be adjusted in the `CMakeLists.txt`.
I guess I'll have to leave it to you to figure this out...

**Comment by rbsheth** [comment]
@jothepro Sorry for the delay here. I do see the branches you pushed - I'll rename them and make a release for the original version. Then we can work on releasing a new version.

**Comment by jothepro** [comment]
@rbsheth do you have an update for me? Do you need some assistance?

**Comment by rbsheth** [comment]
@jothepro I made the two base branches for Hunterization here:
https://github.com/cpp-pm/pugixml/tree/hunter-1.10 (1.10 release)
https://github.com/cpp-pm/pugixml/tree/hunter-1.10-a196b9b (current master branch)

Branches pushed with a hunter* prefix are auto-protected by Github. Can you make a PR with the hunterization changes to the 1.10 release branch, and once merged we can cherry-pick that over to the master branch.

**Comment by jothepro** [comment]
I'm struggling with getting the tests to pass:
https://travis-ci.com/github/jothepro/hunter

It seems like the code-analyser is not happy with the pugixml sourcecode. What do you recommend me to do?
- Opening an issue in the original pugixml repository & waiting for someone to help?
- Ignore the warnings & open a MR anyways to at least fix the broken hunter package?
- roll back to the older 1.8 release that was originally published on hunter & hope the pipeline will get green?

**Comment by rbsheth** [comment]
If it is just the analyzer failing you can submit a testing PR to comment it out.

**Comment by jothepro** [comment]
Ok... This was not at all a pleasant experience, more like branch-juggling...But I think I got it:
https://github.com/cpp-pm/hunter/pull/224
https://github.com/cpp-pm/hunter-testing/pull/61

**Comment by rbsheth** [comment]
@jothepro Yeah it is pretty painful right now to be honest. We're hoping to simplify the process eventually...

**Comment by rbsheth** [comment]
Merged, so should be fixed now.
