### ISSUE TITLE
Issue using Hunter while building

### ISSUE THREAD

**Issue by hvisvana** [cpp-pm/hunter#198]
Hello,
I am currently running the code from [https://github.com/ethereum/aleth](url). 
When I try to build the code, using 
`cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DTESTS=OFF -DMEASURE_GAS=ON -DMEASURE_MEMORY=ON`
it fails and I get the following error, 
`...patience...
...found 1056 targets...
...updating 43 targets...
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/config_file.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/options_description.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/cmdline.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/config_file.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/cmdline.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/value_semantic.o
virtual memory exhausted: Cannot allocate memory

    "/usr/bin/c++" "-std=c++11" "-fPIC"   -fvisibility-inlines-hidden -m64 -pthread -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden  -DBOOST_ALL_NO_LIB=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/value_semantic.o" "libs/program_options/src/value_semantic.cpp"

...failed gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/value_semantic.o...
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/positional_options.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/utf8_codecvt_facet.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/variables_map.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/parsers.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/options_description.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/convert.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/winmain.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/parsers.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/variables_map.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/split.o
...skipped <pbin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden>libboost_program_options-mt-x64.a(clean) for lack of <pbin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden>value_semantic.o...
...skipped <pbin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden>libboost_program_options-mt-x64.a for lack of <pbin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden>value_semantic.o...
...skipped <p/home/vagrant/.hunter/_Base/0897935/53fea1f/d86c769/Build/Boost/__program_options/Source/stage/lib>libboost_program_options-mt-x64.a for lack of <pbin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden>libboost_program_options-mt-x64.a...
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/utf8_codecvt_facet.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/positional_options.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/convert.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/value_semantic.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/winmain.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/split.o
gcc.archive bin.v2/libs/program_options/build/gcc-7.5.0/debug/link-static/threading-multi/visibility-hidden/libboost_program_options-mt-d-x64.a
common.copy /home/vagrant/.hunter/_Base/0897935/53fea1f/d86c769/Build/Boost/__program_options/Source/stage/lib/libboost_program_options-mt-d-x64.a
...failed updating 1 target...
...skipped 3 targets...
...updated 39 targets...
CMakeFiles/Boost-program_options.dir/build.make:113: recipe for target 'Boost-program_options-prefix/src/Boost-program_options-stamp/Boost-program_options-build' failed
make[2]: *** [Boost-program_options-prefix/src/Boost-program_options-stamp/Boost-program_options-build] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Boost-program_options.dir/all' failed
Makefile:83: recipe for target 'all' failed
make[1]: *** [CMakeFiles/Boost-program_options.dir/all] Error 2
make: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/vagrant/.hunter/_Base/0897935/53fea1f/d86c769/Build/Boost/__program_options
[hunter ** FATAL ERROR **] [Directory:/home/vagrant/.hunter/_Base/Download/Hunter/0.23.241/0897935/Unpacked/cmake/projects/Boost/program_options]

------------------------------ ERROR -----------------------------
    https://hunter.readthedocs.io/en/latest/reference/errors/error.external.build.failed.html
------------------------------------------------------------------

CMake Error at /home/vagrant/.hunter/_Base/Download/Hunter/0.23.241/0897935/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  /home/vagrant/.hunter/_Base/Download/Hunter/0.23.241/0897935/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
  /home/vagrant/.hunter/_Base/Download/Hunter/0.23.241/0897935/Unpacked/cmake/modules/hunter_download.cmake:623 (hunter_fatal_error)
  /home/vagrant/.hunter/_Base/Download/Hunter/0.23.241/0897935/Unpacked/cmake/projects/Boost/program_options/hunter.cmake:16 (hunter_download)
  /home/vagrant/.hunter/_Base/Download/Hunter/0.23.241/0897935/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  CMakeLists.txt:73 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/home/vagrant/data/aleth/build/CMakeFiles/CMakeOutput.log".`
(This is just a part of the output)

I am not sure what I am doing wrong and I've had a look at a few previous issues but have not been able to find a solution to this. I am currently using cmake version `3.10.2` and I am running it on MacOS.
Do let me know if any additional information is required to help solve this issue. Thank you.

**Comment by NeroBurner** [comment]
as far as I can see you ran out of Memory (RAM)
```
virtual memory exhausted: Cannot allocate memory

"/usr/bin/c++" "-std=c++11" "-fPIC"   -fvisibility-inlines-hidden -m64 -pthread -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden  -DBOOST_ALL_NO_LIB=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/program_options/build/gcc-7.5.0/release/link-static/threading-multi/visibility-hidden/value_semantic.o" "libs/program_options/src/value_semantic.cpp"
```
try setting `-DHUNTER_JOBS_NUMBER=1` for one of your cmake command line options
https://hunter.readthedocs.io/en/latest/reference/user-variables.html#hunter-jobs-number

**Comment by hvisvana** [comment]
I tried that and it doesn't seem to be helping. I am still running into the same error. I tried running it on an Ubuntu VM too. I seem to get a similar error where virtual memory is exhausted. 
`common.copy /home/vagrant/.hunter/_Base/3511e5f/53fea1f/0d35112/Build/Boost/__log/Source/stage/lib/libboost_log_setup-mt-x64.a
...failed updating 1 target...
...skipped 3 targets...
...updated 286 targets...
CMakeFiles/Boost-log.dir/build.make:113: recipe for target 'Boost-log-prefix/src/Boost-log-stamp/Boost-log-build' failed
make[2]: *** [Boost-log-prefix/src/Boost-log-stamp/Boost-log-build] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Boost-log.dir/all' failed
Makefile:83: recipe for target 'all' failed
make[1]: *** [CMakeFiles/Boost-log.dir/all] Error 2
make: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/vagrant/.hunter/_Base/3511e5f/53fea1f/0d35112/Build/Boost/__log
[hunter ** FATAL ERROR **] [Directory:/home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/projects/Boost/log]

------------------------------ ERROR -----------------------------
    https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html
------------------------------------------------------------------

CMake Error at /home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  /home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
  /home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/modules/hunter_download.cmake:617 (hunter_fatal_error)
  /home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/projects/Boost/log/hunter.cmake:16 (hunter_download)
  /home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  CMakeLists.txt:73 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/home/vagrant/data/aleth/build/CMakeFiles/CMakeOutput.log"`

Also, to be exact, this fails when log is building, 
`Component configuration:

    - atomic                   : not building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : not building
    - exception                : not building
    - fiber                    : not building
    - filesystem               : not building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : not building
    - locale                   : not building
    - log                      : building
    - math                     : not building
    - mpi                      : not building
    - program_options          : not building
    - python                   : not building
    - random                   : not building
    - regex                    : not building
    - serialization            : not building
    - stacktrace               : not building
    - system                   : not building
    - test                     : not building
    - thread                   : not building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building`

Is there some other insight you could provide me with?

**Comment by NeroBurner** [comment]
You've got a VM, try giving it more RAM or give it just one CPU core to compile. Otherwise we have to take a closer look on how the number of threads to build boost with is passed down to bjam

On May 26, 2020 2:53:59 PM GMT+02:00, hvisvana <notifications@github.com> wrote:
>I tried that and it doesn't seem to be helping. I am still running into
>the same error. I tried running it on an Ubuntu VM too. I seem to get a
>similar error where virtual memory is exhausted. 
>`common.copy
>/home/vagrant/.hunter/_Base/3511e5f/53fea1f/0d35112/Build/Boost/__log/Source/stage/lib/libboost_log_setup-mt-x64.a
>...failed updating 1 target...
>...skipped 3 targets...
>...updated 286 targets...
>CMakeFiles/Boost-log.dir/build.make:113: recipe for target
>'Boost-log-prefix/src/Boost-log-stamp/Boost-log-build' failed
>make[2]: *** [Boost-log-prefix/src/Boost-log-stamp/Boost-log-build]
>Error 1
>CMakeFiles/Makefile2:67: recipe for target
>'CMakeFiles/Boost-log.dir/all' failed
>Makefile:83: recipe for target 'all' failed
>make[1]: *** [CMakeFiles/Boost-log.dir/all] Error 2
>make: *** [all] Error 2
>
>[hunter ** FATAL ERROR **] Build step failed (dir:
>/home/vagrant/.hunter/_Base/3511e5f/53fea1f/0d35112/Build/Boost/__log
>[hunter ** FATAL ERROR **]
>[Directory:/home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/projects/Boost/log]
>
>------------------------------ ERROR -----------------------------
>https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html
>------------------------------------------------------------------
>
>CMake Error at
>/home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/modules/hunter_error_page.cmake:12
>(message):
>Call Stack (most recent call first):
>/home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/modules/hunter_fatal_error.cmake:20
>(hunter_error_page)
>/home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/modules/hunter_download.cmake:617
>(hunter_fatal_error)
>/home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/projects/Boost/log/hunter.cmake:16
>(hunter_download)
>/home/vagrant/.hunter/_Base/Download/Hunter/0.23.178/3511e5f/Unpacked/cmake/modules/hunter_add_package.cmake:62
>(include)
>  CMakeLists.txt:73 (hunter_add_package)
>
>
>-- Configuring incomplete, errors occurred!
>See also "/home/vagrant/data/aleth/build/CMakeFiles/CMakeOutput.log"`
>
>Also, to be exact, this fails when log is building, 
>`Component configuration:
>
>    - atomic                   : not building
>    - chrono                   : not building
>    - container                : not building
>    - context                  : not building
>    - contract                 : not building
>    - coroutine                : not building
>    - date_time                : not building
>    - exception                : not building
>    - fiber                    : not building
>    - filesystem               : not building
>    - graph                    : not building
>    - graph_parallel           : not building
>    - headers                  : not building
>    - iostreams                : not building
>    - locale                   : not building
>    - log                      : building
>    - math                     : not building
>    - mpi                      : not building
>    - program_options          : not building
>    - python                   : not building
>    - random                   : not building
>    - regex                    : not building
>    - serialization            : not building
>    - stacktrace               : not building
>    - system                   : not building
>    - test                     : not building
>    - thread                   : not building
>    - timer                    : not building
>    - type_erasure             : not building
>    - wave                     : not building`
>
>Is there some other insight you could provide me with?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cpp-pm/hunter/issues/198#issuecomment-634005828

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rbsheth** [comment]
Yes, as @NeroBurner said you ran out of memory on your VM. Try again with increased memory limits - the build can be quite memory hungry.

**Comment by NeroBurner** [comment]
closed, probably VM with limited RAM
