### ISSUE TITLE
Add "zlog" package

### ISSUE THREAD

**Issue by je-vv** [cpp-pm/hunter#200]
* I'm interested in package `zlog`

* Here is the official site of package:  https://hardysimpson.github.io/zlog
* This package is using Git: https://github.com/HardySimpson/zlog
* Used build system: make
* Unofficial CMake support, but unmaintained and way behind: https://github.com/lisongmin/zlog
* This package has no dependencies

**Comment by rbsheth** [comment]
Solved in #201
