### ISSUE TITLE
How to update Boost to v1.71

### ISSUE THREAD

**Issue by dan-42** [cpp-pm/hunter#21]
Hi,  

I'd like to update boost to the latest version, also containing the new lib variant2.

Previous versions have been stored here: 
https://github.com/hunter-packages/boost
with a branch for each release removing docs, examples, and tests. 
And if needed patches are applied.

If we keep this, could you (@bkotzz @rbsheth ) give me access to it?
So I could also take care of future version.

Or what would your preferred  way to update boost?

**Comment by bkotzz** [comment]
I’ve forked the hunter packages fork into cpp-pm here https://github.com/cpp-pm/boost

**Comment by bkotzz** [comment]
I’ve also invited you to the cpp-pm-packages team, which will give you write access to that fork

**Comment by dan-42** [comment]
Awesome. Thank you @bkotzz. 
PR's comming then the next days :-)

**Comment by dan-42** [comment]
done https://github.com/cpp-pm/hunter/pull/30
