### ISSUE TITLE
Help on downloading private package

### ISSUE THREAD

**Issue by MathieuBahin** [cpp-pm/hunter#211]
Hello,
i'm interested in Hunter, i want to add the dependency in cmake.
I'd like to do the same thing as the exemple directory with my own libraries (git and maybe ftp files).
You can find my project here :
            [-](url)https://drive.google.com/file/d/13PGpwteAvPdm8ecogQsuZd1GvNqUB1fE/view?usp=sharing
so can you help me

**Comment by NeroBurner** [comment]
Maybe that can help you

https://hunter.readthedocs.io/en/latest/faq/how-to-download-private-github-asset.html

**Comment by MathieuBahin** [comment]
thanks so with this command i can download a tar.gz from github for exemple.
Do i need to then do hunter_add_package or find_package and add it in target_link_libraries.

I cloned the basic project  "Quick Start / First Step" it work but then i add my hunter_private_data and it fail with error "Unknown cmake command "hunter_private_data"
Where do i put this command
Thanks

**Comment by NeroBurner** [comment]
I haven't used this feature, but in the documentation it seems that the credentials need to be put into a config file in your home directory (outside of the project repository)
https://hunter.readthedocs.io/en/latest/reference/user-modules/hunter_private_data_password.html

`~/.config/Hunter/passwords.cmake`

**Comment by MathieuBahin** [comment]
Yes but cmake doesn't even know the command it's not user / password error it's unknown command.
I did the passwords.cmake but it seems like the command isn't even executed

**Comment by rbsheth** [comment]
You can specify the passwords file like this: https://hunter.readthedocs.io/en/latest/reference/terminology/hunter-passwords-file.html

If it is giving you unknown command, I'd imagine that the order of calls is wrong. Are you calling `hunter_private_data` after HunterGate?

**Comment by MathieuBahin** [comment]
[CMakeLists.txt](https://github.com/cpp-pm/hunter/files/4817653/CMakeLists.txt)
I am calling it after and the repo is public.

**Comment by rbsheth** [comment]
You're using a Hunter version from 2016 - try upgrading to the newest one.

**Comment by MathieuBahin** [comment]
You're right thanks a lot
