### ISSUE TITLE
CI testing instructions use archived repository.

### ISSUE THREAD

**Issue by jothepro** [cpp-pm/hunter#212]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

I'm currently in the process on contributing a package update, and I stumbled across this line in the instructions:

> Since we are adding a new package we have to create new CI configs for it. Fetch the branch pkg.template and substitute all foo strings with hunter_box_1:
>
> `git remote add ci https://github.com/ingenue/hunter`

https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html#fetch-ci-configs

I wonder if it is correct that tests still reply on the archived repository `ingenue/hunter`.

It did work for me, but I guess this is not the best way to do it, is it?

**Comment by rbsheth** [comment]
No, it should be https://github.com/cpp-pm/hunter-testing

**Comment by jothepro** [comment]
Nice, good to know that. I'll try to fix the documentation. 👍
