### ISSUE TITLE
Reference to abandoned hunter-cache in documentation & code

### ISSUE THREAD

**Issue by jothepro** [cpp-pm/hunter#216]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

While replacing the references to the archived repo for #212 I found [this](https://hunter.readthedocs.io/en/latest/overview/binaries.html?highlight=ingenue%2Fhunter-cache#details).
The documentation mentions a cache-server repository, that seems to be the default when caching binaries on a server is enabled. The link redirects to a weird graveyard of projects apparently from the original author of hunter.

I'm also wondering if [this](https://github.com/cpp-pm/hunter/blob/master/cmake/modules/hunter_finalize.cmake#L25) reference to the seemingly discarded cache repo is still valid.

I'm not sure if and how I should correct these mentions, since I've not used remote caches yet.

**Comment by rbsheth** [comment]
We currently use a private cache for our builds. It would be helpful to revive the public cache server to accelerate people's build times. I haven't come up with a clean way to do this right now. Open to suggestions!
