### ISSUE TITLE
`json_fwd.hpp` missing from nlohmann/json since 3.8.0

### ISSUE THREAD

**Issue by deepbluev7** [cpp-pm/hunter#218]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://hunter.readthedocs.io/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://hunter.readthedocs.io/en/latest/packages.html). **Yes**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **Yes**
`https://github.com/cpp-pm/hunter/archive/v0.23.260.tar.gz`/`13775235910a3fa85644568d1c5be8271de72e1c`

---

https://github.com/cpp-pm/hunter/pull/208 changed the download of nlohmann/json to download only the header from github instead of downloading the full package. This means now only the `json.hpp` header is included. The `json_fwd.hpp` header is missing. This not only can make the build slower in some cases, it can also lead to conflicts, where you try to figure out, if `json_fwd.hpp` is in the include path and preferring to include that one. As a result of the header missing from the hunter include path, it may find the system `json_fwd.hpp`. As a result of this you may get funny template errors, if the versions don't match exactly.

It would be great, if hunter could include `json.hpp` and `json_fwd.hpp` in the nlohmann/json package.

**Comment by rbsheth** [comment]
@themarpe Is this easy to do?

**Comment by themarpe** [comment]
@deepbluev7 #208 did not change the download to header only. It still downloads the whole source repository, execute CMake build and install. 
Looking through CMakeLists.txt for previous released version (3.7.0) vs 3.8.0 there doesn't seem to be the difference regarding multiple headers. By default both versions have options for "JSON_MultipleHeaders" set to OFF. 

Two options to go about from here:
 - (Changes on your end) Add a "LOCAL" config (cmake/Hunter/config.cmake) in your codebase and specify the additional CMAKE_ARGS flag for nlohmann package: JSON_MultipleHeaders=ON (More information on this topic here: https://hunter.readthedocs.io/en/latest/reference/user-modules/hunter_config.html)
 - (Changes on Hunter end) Default passed flags could be altered in Hunter to specify JSON_MultipleHeaders=ON as default (You'd have to wait till next release)

For the second option, the behaviour of only including json.hpp when having the library compiled with JSON_MultipleHeaders=ON should match the behaviour of JSON_MultipleHeaders=OFF, to not introduce breaking changes to users of this package.

**Comment by deepbluev7** [comment]
@themarpe I see, that makes sense. It seems I misinterpreted the PR and since the breakage was new to me, I blamed it on that change. Sorry about that. Option 1 is acceptable for now. If you can implement Option 2 for future releases, that would be great, but I'm also fine with sticking to option 1 for the foreseeable future. Option 2 shouldn't introduce any breakage as far as I'm aware, since it only adds an additional header, but applications rely on weird implementation details at times, so who knows :D 

Thank you for your quick response, that was very helpful!

**Comment by themarpe** [comment]
We could add JSON_MultipleHeaders=ON as default and maybe update the docs to inform users of ability to change to old single include json.hpp option. I have a feeling that in some rare cases the multiple header include won't perform in same way as single include.
On the other hand, users requiring multiple headers could add the CMAKE_ARGS to customize the build.
Both options are in the end quite similar.

@rbsheth I think we can leave it as is for now - if there will be more interest for multiple headers, we can make the argument as default, otherwise its up to user to customize.

**Comment by rbsheth** [comment]
@themarpe Thanks for the thoughtful responses! I agree to leave it up to the user to configure through options for now. Closing.
