### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by dbyoung720** [cpp-pm/hunter#229]
Ask a mentally retarded question, how to use this thing?
For example, I under WIN10, how to use it to compile ZLIB library?

**Comment by NeroBurner** [comment]
see the documentation in the Quickstart section

https://hunter.readthedocs.io/en/latest/

**Comment by dbyoung720** [comment]
Read it, didn't understand

**Comment by NeroBurner** [comment]
please be more specific. What exactly is the problem? What did you try?

**Comment by NeroBurner** [comment]
maybe the documentation for the ZLIB package will help you

https://hunter.readthedocs.io/en/latest/packages/pkg/ZLIB.html#index-0

**Comment by rbsheth** [comment]
I think the getting started documentation is decent to get you up and running. You will need some knowledge of CMake to use Hunter. It would look something like:
```
include(HunterGate)
HunterGate(...)

hunter_add_package(ZLIB)
find_package(ZLIB CONFIG REQUIRED)
```

**Comment by rbsheth** [comment]
Closing...

**Comment by rbsheth** [comment]
If you need more help, let us know.
