### ISSUE TITLE
Default Boost version is 1.72 - Boost 1.74 has been released

### ISSUE THREAD

**Issue by madmongo1** [cpp-pm/hunter#257]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://hunter.readthedocs.io/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://hunter.readthedocs.io/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

As per the title. Boost-1.74 is now out. There have been some significant improvements and bug fixes. Notably, asio/beast now have correct support for c++20 coroutines and concepts.

**Comment by Bjoe** [comment]
I started a PR #316 
Hopefully I can fix also #185 with the newer boost version.

**Comment by Bjoe** [comment]
@madmongo1 I added boost 1.74. But as I wrote on #185 ... I'm not yet an expert of the github actions and I have trouble lg run the ci builds .... so If you like and it would be great when you test my PR #316

**Comment by Bjoe** [comment]
There is a new hunter version with the newest boost 1.75. https://github.com/cpp-pm/hunter/releases/tag/v0.23.290 Also boost 1.74 is included.
Try out and close this issue if it solved for you.

**Comment by NeroBurner** [comment]
Closing. With PR https://github.com/cpp-pm/hunter/pull/500 merged and released with https://github.com/cpp-pm/hunter/releases/tag/v0.23.319 Hunter provides Boost v1.78.0
