### ISSUE TITLE
hunter_add_package(GITHUB ) simplification proposal 

### ISSUE THREAD

**Issue by andreyryabov** [cpp-pm/hunter#265]
Why can't I simply add package from github without Hunter Gate?

`hunter_add_package(GITHUB https://github.com/jaegertracing/jaeger-client-cpp.git)`

It would be much easier to get updated versions of packages.

**Comment by NeroBurner** [comment]
you could use a local config file with the `hunter_config()` command

https://hunter.readthedocs.io/en/latest/reference/user-modules/hunter_config.html

just using the latest git is not reproducible. I don't want to have my release build break 2 years in the future because of a dependency that I have added with Hutner

**Comment by andreyryabov** [comment]
I'm using hunter_config with submodules and find it not really convenient requires some extra work to set up submodules. 
Ideally I'd like to do something like this:

hunter_add_package(GITHUB https://github.com/jaegertracing/jaeger-client-cpp.git TAG v0.6.0)

**Comment by chfast** [comment]
Something like this is possible. It would be something between Hunter and ExternalProject. Someone just has to write it.

**Comment by NeroBurner** [comment]
currently you could use the direct link and generate the sha1sum manually using `hunter_config()` https://hunter.readthedocs.io/en/latest/reference/user-modules/hunter_config.html

```cmake
hunter_config(jaeger-client-cpp
    URL  https://github.com/jaegertracing/jaeger-client-cpp/archive/v0.6.0.tar.gz
    SHA1 9de8d545bcc91289b04c4deb592411235722d2c3)
```

and then use `hunter_add_package(jaeger-client-cpp)` in your project

**Comment by andreyryabov** [comment]
> Something like this is possible. It would be something between Hunter and ExternalProject. Someone just has to write it.

Hunter is a great wrapper for ExternalProject. The only problem is Hunber Gate where you have to configure the packages you need with `hunter_config` which is I think an unnecessary level of indirection.

**Comment by andreyryabov** [comment]
> currently you could use the direct link and generate the sha1sum manually using `hunter_config()` https://hunter.readthedocs.io/en/latest/reference/user-modules/hunter_config.html

I use `hunter_config` and `hunter_add_package` I feel it's overcomplicated. I'd love to have simplified configuration in  `hunter_add_package`. 

All packages I use I have to list in `hunter_config` to ensure sure versions. Also I install open source packages from my forks. That makes completely useless for me.

**Comment by andreyryabov** [comment]
> Something like this is possible. It would be something between Hunter and ExternalProject. Someone just has to write it.

I abandoned Hunter and wrote a small wrapper around ExternalProject_add to handle dependencies. 
@chfast thanks for advice!

**Comment by chfast** [comment]
> I abandoned Hunter and wrote a small wrapper around ExternalProject_add to handle dependencies.

Does your wrapper builds the dependency during CMake configuration?
