### ISSUE TITLE
hunter packages not visible in XCode

### ISSUE THREAD

**Issue by andreyryabov** [cpp-pm/hunter#266]
How I make hunter packages visible as targets/libraries in Xcode ?

**Comment by NeroBurner** [comment]
Currently that's not possible

What would be the use case for these visible targets?
Are targets found by find_package visible in xcode?

**Comment by andreyryabov** [comment]
That would solve package management for XCode, like alternative to CocoaPods. 
Packages found by find_packages are also not visible. 
The use case if following:
1. I declare a static or a dynamic library for a framework in CMake that have dependencies from hunter.
2. Generate XCode project. 
3. The project builds by XCode no problem.
4. If I refer this project from other XCode project as a dependency I get a PROBLEM! hunter dependencies are not transitively visible.

**Comment by andreyryabov** [comment]
Found workaround by using ExternalProject_add instead of Hunter. Closing the issue. 
Thank you.
