### ISSUE TITLE
Consolidate CI providers

### ISSUE THREAD

**Issue by bkotzz** [cpp-pm/hunter#27]
We currently use appveyor for CI on Windows, and Travis for CI on Mac/iOS/Linux. This means that you need to enable both on any fork you create, to run CI on a package. 

Travis has released Windows support, a la https://blog.travis-ci.com/2018-10-11-windows-early-release, so we could experiment with running the windows builds on Travis as well, and not need to support appveyor.

**Comment by hjmallon** [comment]
Apvveyor is hellish slow too, Travis will run many configurations (around 5?) at once, but Appveyor only runs 1. Boost test builds take ~5hrs for me on Appveyor, but far less on Travis.

**Comment by cristianadam** [comment]
I would suggest using GitHub Actions, see https://github.com/cpp-pm/hunter/issues/40 


Virtual environment | YAML workflow label
-- | --
Windows Server 2019 | windows-latest
Ubuntu 18.04 | ubuntu-latest or ubuntu-18.04
Ubuntu 16.04 | ubuntu-16.04
macOS Catalina 10.15 | macos-latest

Each virtual machine has the same hardware resources available:

 * 2-core CPU
 * 7 GB of RAM memory
 * 14 GB of SSD disk space

Each job in a workflow can run for up to 6 hours of execution time.

I've blogged about how to use C++ and CMake with GitHub Actions here: https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/

**Comment by rbsheth** [comment]
Closed with #250, everything is on Github Actions now.
