### ISSUE TITLE
Update "doctest" package

### ISSUE THREAD

**Issue by AndrewCr0w** [cpp-pm/hunter#294]
* I'm interested in new version (2.4.0) of package `doctest`
* Here is the official site of package https://github.com/onqtam/doctest

* This package is using [Git]: https://github.com/onqtam/doctest.git

* Official GitHub repository: https://github.com/onqtam/doctest

* Used build system: [CMake]

* I have no information about dependencies, it's header only.

---

**Comment by Bjoe** [comment]
I update doctest to 2.4.4. PR #353 is started.

**Comment by rbsheth** [comment]
Closed by #353
