### ISSUE TITLE
Update "Lua" package to 5.3.5

### ISSUE THREAD

**Issue by caseymcc** [cpp-pm/hunter#31]
I need a fork of https://github.com/hunter-packages/lua to https://github.com/cpp-pm/lua repo in order to update the changes needed for the latest version.

**Comment by bkotzz** [comment]
The fork is created here https://github.com/cpp-pm/lua. I’ve also invited you to the cpp-pm-packages group which gives you write access to all the forks in cpp-pm (except protected branches), so feel free to push your feature branch directly to cpp-pm/lua and open a PR, without having to make your own fork of it. 

Also this package seems like a good example of one that would work well with the proposal here https://github.com/cpp-pm/hunter/issues/28. Any thoughts?

**Comment by caseymcc** [comment]
@bkotzz 

need to update the appveyor and travis files, do we have a plan for that yet?

**Comment by caseymcc** [comment]
never-mind saw the intermediate steps in https://github.com/cpp-pm/hunter/issues/9

**Comment by rbsheth** [comment]
Done in #32
