### ISSUE TITLE
How to use this locally?

### ISSUE THREAD

**Issue by marcovc** [cpp-pm/hunter#313]
Hi,

I've recently discovered Hunter, and I think it's a nice idea, but I can't afford having to wait for days to be able to use a new package or a new version of a package not yet in this repo.

Is there any way I can locally tell hunter how to download and install the package?

**Comment by NeroBurner** [comment]
Yes, there is: [HUNTER_ROOT](https://hunter.readthedocs.io/en/latest/reference/user-variables.html?highlight=HUNTER_ROOT#hunter-root)

**Comment by NeroBurner** [comment]
or if it is just your personal local project you can use [hunter_config()](https://hunter.readthedocs.io/en/latest/reference/user-modules/hunter_config.html)

Usage example: https://github.com/cpp-pm/hunter/blob/master/docs/old-wiki/example.custom.config.id.md

**Comment by marcovc** [comment]
Thanks. I ended up cloning this repo and updating there. Then it's just the same work to push a PR there and here, and has the added benefit of potentially being useful to others, and I no longer have to wait for PR approval.
