### ISSUE TITLE
Update "glm" package

### ISSUE THREAD

**Issue by HeBomou** [cpp-pm/hunter#330]
* I'm interested in package `glm`, which has a new release glm 0.9.9.8. Glm has removed install scripts since 0.9.9.6, but I'd like to hunterize it. (I'm following this [guide](https://hunter.readthedocs.io/en/latest/creating-new/patch.html))

* This package is using Git: https://github.com/g-truc/glm

* Could you please create a branch named "hunter-0.9.9.8" in cpp-pm/glm? So that I can submit a PR to it.

**Comment by rbsheth** [comment]
@HeBomou https://github.com/cpp-pm/glm/tree/hunter-0.9.9.8

**Comment by HeBomou** [comment]
@rbsheth I've submitted a PR cpp-pm/glm#2

**Comment by rbsheth** [comment]
@HeBomou Thanks and happy new year! Here is the release: https://github.com/cpp-pm/glm/releases/tag/v0.9.9.8-p0

**Comment by HeBomou** [comment]
Happy new year!
I've made a pr to hunter: cpp-pm/hunter#342

**Comment by rbsheth** [comment]
Thanks!
