### ISSUE TITLE
Static boost libraries cannot be found after compilation in ppc64le architecture

### ISSUE THREAD

**Issue by viniciusferrao** [cpp-pm/hunter#351]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://hunter.readthedocs.io/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://hunter.readthedocs.io/en/latest/packages.html). **Yes**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **Yes**

* I've created [SSCCE](http://www.sscce.org/) reproducing the issue:
```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.5)

include(cmake/cable/bootstrap.cmake)

include(CableBuildInfo)
include(CableBuildType)
include(CableToolchains)
include(HunterGate)

include(defaults/HunterCacheServers)

cable_configure_toolchain(DEFAULT cxx11)

set(HUNTER_CONFIGURATION_TYPES Release CACHE STRING "Build type of Hunter packages")
set(HUNTER_JOBS_NUMBER 6 CACHE STRING "Number of parallel builds used by Hunter")
HunterGate(
    URL "https://github.com/cpp-pm/hunter/archive/v0.23.291.tar.gz"
    SHA1 "4f57243b24a02b9c7ec5ea02c09d5c77c6a97cba"
    LOCAL
)

project(foo)

cable_set_build_type(DEFAULT Release CONFIGURATION_TYPES Release RelWithDebInfo)

hunter_add_package(Boost COMPONENTS system filesystem thread)
find_package(Boost CONFIG REQUIRED COMPONENTS system filesystem thread)

hunter_add_package(jsoncpp)
find_package(jsoncpp CONFIG REQUIRED)

hunter_add_package(ethash)
find_package(ethash CONFIG REQUIRED)
```

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* https://pastebin.com/6DvFUn3c

I've checked that the first error in logs **IS NOT** `external.build.failed`. **Yes**

* I'm building on Linux (RHEL 8.3)
* I'm using CMake from snapd (snapcraft.io)
* CMake version: 3.19.3

* I'm not using toolchain (I think...)

I'm using the next command line on generate step:
```
cmake .. -DHUNTER_STATUS_DEBUG=ON -DHUNTER_NO_TOOLCHAIN_ID_RECALCULATION=OFF
```

---

I've found this while trying to compile `nsfminer` and first reported the issue there: https://github.com/no-fee-ethereum-mining/nsfminer/issues/30

But after some testing I think this may be a Hunter issue.

If there's something additional to be made please let me know. I've done the best to report this correctly. In the paste there's also the output of `CMakeOutput.log`.

Thanks!

**Comment by rbsheth** [comment]
Interesting, I never tried compiling on ppc but the whole point is for Hunter to not care about the architecture it is compiling for. Thanks for the bug report! We'll have to investigate.

@Bjoe any ideas, since you were recently in the Boost Hunter files?

**Comment by Bjoe** [comment]
It's using the `FindBoost` from hunter see `.hunter/_Base/Download/Hunter/0.23.291/4f57243/Unpacked/cmake/find/FindBoost.cmake`. This `FindBoost` is outdated as I said. See also my [comment](https://github.com/cpp-pm/hunter/issues/141#issuecomment-588067523) in issue #141

Can you please try with enabled: `USE_CONFIG_FROM_BOOST=ON` See `Boost-filesystem-useBoostConfig` in git -> https://github.com/cpp-pm/hunter/tree/master/examples/Boost-filesystem-useBoostConfig or see in the hunter doc: https://hunter.readthedocs.io/en/latest/packages/pkg/Boost.html#cmake-options

Btw. If you are using `USE_CONFIG_FROM_BOOST=ON` and you didn't need `system` and `thread` in your project, you can remove it. `USE_CONFIG_FROM_BOOST=ON` is build and add automatically the dependencies.

**Comment by viniciusferrao** [comment]
Hi @Bjoe thanks for the tip. I tried what you've said but It was a no go. Please correct me if I've done something wrong:

Added the following do CMakeLists.txt:

```
HunterGate(
    URL "https://github.com/cpp-pm/hunter/archive/v0.23.293.tar.gz"
    SHA1 "e8e5470652db77149d9b38656db2a6c0b7642693"
    LOCAL
)
set(Boost_USE_STATIC_LIBS ON)
```

And invoked `cmake` with: `cmake .. -DUSE_CONFIG_FROM_BOOST=ON -DHUNTER_STATUS_DEBUG=ON -DHUNTER_NO_TOOLCHAIN_ID_RECALCULATION=OFF`

Same error was generated.

**Comment by Bjoe** [comment]
@viniciusferrao No, sorry this is wrong how you add this configuration. You must set this `Boost_USE_STATIC_LIBS=ON` on `hunter_config()`, like this example:
```
hunter_config(Boost
    VERSION ${HUNTER_Boost_VERSION}
    CMAKE_ARGS USE_CONFIG_FROM_BOOST=ON
)
```

See documentation about `hunter_config()` here https://hunter.readthedocs.io/en/latest/reference/user-modules/hunter_config.html

**Comment by viniciusferrao** [comment]
Hi @Bjoe thanks again, but I'm too amateurish with CMake and Hunter.

The example on the pointed reference is a broken link, the Wiki page appears to be removed: https://github.com/ruslo/hunter/wiki/example.custom.config.id; I tried to find this page but I was unsuccessful.

I've trying adding the setting on `CMakeFiles.txt` but that was stupid.

After I've tried to add the settings to: `./cmake/Hunter/config.cmake`:

```
[root@rhvpower nsfminer]# cat ./cmake/Hunter/config.cmake
hunter_config(CURL VERSION ${HUNTER_CURL_VERSION} CMAKE_ARGS HTTP_ONLY=ON CMAKE_USE_OPENSSL=OFF CMAKE_USE_LIBSSH2=OFF CURL_CA_PATH=none)
hunter_config(Boost
    VERSION ${HUNTER_Boost_VERSION}
    CMAKE_ARGS USE_CONFIG_FROM_BOOST=ON
)
```

But it seems to have no effect at all. The issue persisted. Is there anything else missing?

**Comment by rbsheth** [comment]
https://github.com/cpp-pm/gate#usage-custom-config

**Comment by viniciusferrao** [comment]
Alright guys. It worked.

After reading the page shared by @rbsheth I've done the following:

* Keep the modifications on `./cmake/Hunter/config.cmake`:

```[root@rhvpower nsfminer]# cat ./cmake/Hunter/config.cmake
hunter_config(CURL VERSION ${HUNTER_CURL_VERSION} CMAKE_ARGS HTTP_ONLY=ON CMAKE_USE_OPENSSL=OFF CMAKE_USE_LIBSSH2=OFF CURL_CA_PATH=none)
hunter_config(Boost
    VERSION ${HUNTER_Boost_VERSION}
    CMAKE_ARGS USE_CONFIG_FROM_BOOST=ON
)
```


* Only added LOCAL at the end of `HunterGate` on `CMakeFiles.txt`:

```
HunterGate(
    URL "https://github.com/cpp-pm/hunter/archive/v0.23.293.tar.gz"
    SHA1 "e8e5470652db77149d9b38656db2a6c0b7642693"
    LOCAL
)
```

Accordingly to the documentation the `LOCAL` keyword searches for `${CMAKE_CURRENT_LIST_DIR}/cmake/Hunter/config.cmake`; which is where I've done the changes.

So this is solved now.

The remaining question now is:
* Is this an issue with the usage of Hunter and specifically Boost?
* The upstream software have wrongly added Boost or this is a Hunter issue?
* If the right way to compile the software is with the options shared by @Bjoe we may need some documentation regarding this?

Thanks!

**Comment by Bjoe** [comment]
@rbsheth As you see again.... we should use as default the boost config from boost ....

**Comment by rbsheth** [comment]
@Bjoe should we add that to the boost hunter.cmake?

**Comment by Bjoe** [comment]
@rbsheth I tried and it works, but read my https://github.com/cpp-pm/hunter/pull/316#issuecomment-757888431 ... My next idea/try is, set the cmake policiy in the BoostConfig.cmake in boost .... so need to patch boost sources again and if this works, then I will bug report this to the boost project.

Hopefully I found some time for this .... to busy and unfortunately there are still pull request open #122 #168 #173  from me where I like to work on...

**Comment by viniciusferrao** [comment]
Hi guys, just as a curiosity. What will be the approach here? As today I have to keep a separate branch for a software that I use that relies on Hunter because the PR wasn't accepted.

I know that's my problem :)

Thanks all.

**Comment by rbsheth** [comment]
Which PR are you talking about? #154 was merged a while ago.

**Comment by Bjoe** [comment]
@viniciusferrao I would like to have as default `USE_CONFIG_FROM_BOOST=ON` in Hunter. But unfortunately it will break for example `BoostProcess` because it uses boost as depend library but the project is set `cmake_minimum_version(3.0)` see https://github.com/alamaison/boost-process/blob/f1a4eafbedfa277b9890c6bc01a44356f53acd7b/CMakeLists.txt#L6 and then the build got an `IN_LIST` error. This feature is used in the boost config module.

My idea, set the policy for `IN_LIST` in the boost config module (and maybe also create a bug report in boost).
Maybe I will find somehow some time to do this....

**Comment by kapoor7997** [comment]
@viniciusferrao Hi, 

I am using the latest hunter library v0.23.300 and getting this issue.
I am getting the following error during the cmake process (I am using latest cmake 3.20.2)

-----------------------------Start of Error----------------------------------------
CMake Error at src/jsonrpccpp/CMakeLists.txt:144 (add_library):
  Target "client" links to target "intsizeof::intsizeof" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
CMakeFiles/libjson-rpc-cpp-Release.dir/build.make:94: recipe for target 'libjson-rpc-cpp-Release-prefix/src/libjson-rpc-cpp-Release-stamp/libjson-rpc-cpp-Release-configure' failed
make[2]: *** [libjson-rpc-cpp-Release-prefix/src/libjson-rpc-cpp-Release-stamp/libjson-rpc-cpp-Release-configure] Error 1
make[2]: Leaving directory '/home/s2600bottom/.hunter/_Base/1151d53/53fea1f/4646e4e/Build/libjson-rpc-cpp/Build'
CMakeFiles/Makefile2:85: recipe for target 'CMakeFiles/libjson-rpc-cpp-Release.dir/all' failed
make[1]: *** [CMakeFiles/libjson-rpc-cpp-Release.dir/all] Error 2
make[1]: Leaving directory '/home/s2600bottom/.hunter/_Base/1151d53/53fea1f/4646e4e/Build/libjson-rpc-cpp/Build'
Makefile:93: recipe for target 'all' failed
make: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/s2600bottom/.hunter/_Base/1151d53/53fea1f/4646e4e/Build/libjson-rpc-cpp
[hunter ** FATAL ERROR **] [Directory:/home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/projects/libjson-rpc-cpp]

------------------------------ ERROR -----------------------------
    https://hunter.readthedocs.io/en/latest/reference/errors/error.external.build.failed.html
------------------------------------------------------------------

CMake Error at /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
  /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/modules/hunter_download.cmake:623 (hunter_fatal_error)
  /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/projects/libjson-rpc-cpp/hunter.cmake:61 (hunter_download)
  /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  CMakeLists.txt:68 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/opt/pkg/hostSide/ethminer-fpga/CMakeFiles/CMakeOutput.log".

--------------------------------End of error---------------------------------------------

Did you resolve this issue?
Any solutions!!!!!!!!!!!!!!!!!!!

**Comment by viniciusferrao** [comment]
> @viniciusferrao Hi,
> 
> I am using the latest hunter library v0.23.300 and getting this issue.
> I am getting the following error during the cmake process (I am using latest cmake 3.20.2)
> 
> -----------------------------Start of Error----------------------------------------
> CMake Error at src/jsonrpccpp/CMakeLists.txt:144 (add_library):
> Target "client" links to target "intsizeof::intsizeof" but the target was
> not found. Perhaps a find_package() call is missing for an IMPORTED
> target, or an ALIAS target is missing?
> 
> -- Generating done
> CMake Generate step failed. Build files cannot be regenerated correctly.
> CMakeFiles/libjson-rpc-cpp-Release.dir/build.make:94: recipe for target 'libjson-rpc-cpp-Release-prefix/src/libjson-rpc-cpp-Release-stamp/libjson-rpc-cpp-Release-configure' failed
> make[2]: *** [libjson-rpc-cpp-Release-prefix/src/libjson-rpc-cpp-Release-stamp/libjson-rpc-cpp-Release-configure] Error 1
> make[2]: Leaving directory '/home/s2600bottom/.hunter/_Base/1151d53/53fea1f/4646e4e/Build/libjson-rpc-cpp/Build'
> CMakeFiles/Makefile2:85: recipe for target 'CMakeFiles/libjson-rpc-cpp-Release.dir/all' failed
> make[1]: *** [CMakeFiles/libjson-rpc-cpp-Release.dir/all] Error 2
> make[1]: Leaving directory '/home/s2600bottom/.hunter/_Base/1151d53/53fea1f/4646e4e/Build/libjson-rpc-cpp/Build'
> Makefile:93: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> [hunter ** FATAL ERROR **] Build step failed (dir: /home/s2600bottom/.hunter/_Base/1151d53/53fea1f/4646e4e/Build/libjson-rpc-cpp
> [hunter ** FATAL ERROR **] [Directory:/home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/projects/libjson-rpc-cpp]
> 
> ## ------------------------------ ERROR -----------------------------
> https://hunter.readthedocs.io/en/latest/reference/errors/error.external.build.failed.html
> CMake Error at /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
> Call Stack (most recent call first):
> /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
> /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/modules/hunter_download.cmake:623 (hunter_fatal_error)
> /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/projects/libjson-rpc-cpp/hunter.cmake:61 (hunter_download)
> /home/s2600bottom/.hunter/_Base/Download/Hunter/0.23.300/1151d53/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
> CMakeLists.txt:68 (hunter_add_package)
> 
> -- Configuring incomplete, errors occurred!
> See also "/opt/pkg/hostSide/ethminer-fpga/CMakeFiles/CMakeOutput.log".
> 
> --------------------------------End of error---------------------------------------------
> 
> Did you resolve this issue?
> Any solutions!!!!!!!!!!!!!!!!!!!

The solution was posted by me seven messages behind: https://github.com/cpp-pm/hunter/issues/351#issuecomment-772103794

Unfortunately the PR wasn't merged.

**Comment by kapoor7997** [comment]
@viniciusferrao 

Thanks for the repply.
I already have LOCAL after the SHA1. But I still get these errors.
I was using a hunter v0.23.6 before. As soon as I change it to hunter v0.23.300 which is the latest (I had to change as V0.23.6 was using bintray for boost library and bintray.com is shut down for good). So I switched to hunter v0.23.300. And then I get this issue when I try to build. 


You mentioned this in the  #351 (comment) reply

Keep the modifications on ./cmake/Hunter/config.cmake:
hunter_config(CURL VERSION ${HUNTER_CURL_VERSION} CMAKE_ARGS HTTP_ONLY=ON CMAKE_USE_OPENSSL=OFF CMAKE_USE_LIBSSH2=OFF CURL_CA_PATH=none)
hunter_config(Boost
    VERSION ${HUNTER_Boost_VERSION}
    CMAKE_ARGS USE_CONFIG_FROM_BOOST=ON
)

Where is the ./cmake/Hunter/config.cmake? Do I have to enter these changes?

**Comment by NeroBurner** [comment]
is this issue still valid with the latest Hunter? If so, what would be needed to resolve the open issue?

**Comment by NeroBurner** [comment]
Mysterious. The error is at `Boost::system` build time as far as I can see

Could you try to build the Boost example directly from hunter? Just to be sure we have the same CMake config to work with

```sh
git clone --recursive https://github.com/cpp-pm/hunter.git
cd hunter/examples/Boost-chrono-useBoostConfig/
cmake -H. -Bbuild -DHUNTER_ENABLED=ON -DHUNTER_STATUS_DEBUG=ON |& tee build.log
```

Afterwards please upload the `build.log` file so we can do some data forensics ;)

**Comment by NeroBurner** [comment]
The `BoostConfig.cmake` file doesnt find the boost system Library. Can you show me what is installed in the library path

I think it should be this path, according to your logs

```sh
ls /root/hunter/_Base/xxxxxxx/19404f8/314d74e/Install/lib
```

**Comment by NeroBurner** [comment]
so the library is definitely there. Next step in debugging :)

please add the `config.cmake` from `examples/Boost-chrono-useBoostConfig` https://github.com/cpp-pm/hunter/blob/master/examples/Boost-chrono-useBoostConfig/config.cmake to the `examples/Boost-system` example and try it again.

There should be no `FindBoost.cmake` calls in the logs, rather the `BoostConfig.cmake` file should be used

Please report back if it works, and add the logs from the `Boost-system` example cmake call with the added `config.cmake`

**Comment by NeroBurner** [comment]
wohoo it works! You're welcome

**Comment by NeroBurner** [comment]
In this case no, I don't think so. We already have `examples/Boost-chrono-useBoostConfig` to test the `useBoostConfig` parameter (as an alteration to the `examples/Boost-chrono` one). So adding a `examples/Boost-system-useBoostConfig` would be redundant

I'd personally like to set the default of `USE_BOOST_CONFIG=ON`. Do you know if the `BoostProcess` error is fixed mentioned by @Bjoe in https://github.com/cpp-pm/hunter/issues/351#issuecomment-815567125 ?

@rbsheth do you have an opinion about this? As I think the `OFF ` default will regularly lead to confusion with hunter and Boost with users
