### ISSUE TITLE
Add "aws_lambda_cpp" package

### ISSUE THREAD

**Issue by kevinkjt2000** [cpp-pm/hunter#379]
* I'm interested in package `aws_lambda_cpp`
* Here is the official site of package https://github.com/awslabs/aws-lambda-cpp

* This package is using Git: https://github.com/awslabs/aws-lambda-cpp

* Official GitHub repository: https://github.com/awslabs/aws-lambda-cpp

* Used build system: CMake

* This package has these dependencies:

  * `curl` (required, available in Hunter: https://hunter.readthedocs.io/en/latest/packages/pkg/CURL.html)

---

I do not work for AWS, nor am I a maintainer on the linked GitHub. I also have not broached this idea with any maintainers of aws-lambda-cpp. I have begun the packaging process in my fork of hunter https://github.com/kevinkjt2000/hunter/tree/pr.aws_lambda_cpp, this is when I realized I would need to hunterize the package to add the curl dependency.

**Comment by rbsheth** [comment]
If you can Hunterize the library I can add a fork. We've been looking at incorporating the AWS C++ SDK into Hunter as well.

**Comment by kevinkjt2000** [comment]
I plan to Hunterize it. Do I need to do that before a fork is created in the hunter organization? I'll fork to my own username and make a `hunter` branch, if that's desired.

P.S. The AWS C++ SDK might be next on my list when I get around to interacting with DynamoDB in the Discord bot that I'm working on https://github.com/kevinkjt2000/serverless-discord.

**Comment by rbsheth** [comment]
@kevinkjt2000 I took a look at your fork - looks like the AWS lambda package has appropriate CMake files already? If so, you can just open a PR against this repo with your changes.

**Comment by kevinkjt2000** [comment]
What about the dependency on curl? Does this not require hunter-izing the package? Hence this fork request? It's my understanding that I need to add HunterGate in a `hunter` branch to capture this dependency.

**Comment by rbsheth** [comment]
Ah ok, yes `cURL` would need a fork. Here's a fork repo for you: https://github.com/cpp-pm/aws-lambda-cpp
