### ISSUE TITLE
Suggestion: Add a default testing target for Universal 2 macOS builds

### ISSUE THREAD

**Issue by hjmallon** [cpp-pm/hunter#385]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

We currently use hunter a lot with CMAKE_OSX_ARCHITECTURES set to "arm64;x86_64" (i.e. universal 2). Perhaps we should add a polly toolchain containing this to our testing toolchains as it can throw up some interesting breakages (especially in projects that do not use cmake [Boost] or projects that do not support it due to asm requirements etc [libjpeg-turbo])?

**Comment by rbsheth** [comment]
I'd be down. Wanna send over a PR? 😄
