### ISSUE TITLE
Add OpenCV 4.1.1 

### ISSUE THREAD

**Issue by kumaakh** [cpp-pm/hunter#4]
OpenCV 4.0.0 package is already there. It will be useful to also add support for 4.1.1. 
Trying to figure out how to do it with help from  @headupinclouds . Pls. assign the task to me

**Comment by kumaakh** [comment]
Please create a branch for this work as here: 
https://github.com/hunter-packages/opencv/tree/hunter-4.1.1

**Comment by rbsheth** [comment]
Hi @kumaakh, I've added a new fork and the `hunter-4.1.1` branch here: 
https://github.com/cpp-pm/opencv/tree/hunter-4.1.1
I've also invited you to the group `cpp-pm-packages` that has Write access to `cpp-pm` forks. Please create your PR against that branch and I will review!

**Comment by kumaakh** [comment]
I am done with the ci test on travis and appveyor. All configs accept opencv-ffmpeg are passing
https://ci.appveyor.com/project/kumaakh/hunter/builds/27215873
https://travis-ci.org/kumaakh/hunter/builds/581399681
will submit PR to cpp-pm

**Comment by rbsheth** [comment]
Done in #8. Thanks for your contribution!
