### ISSUE TITLE
Use github actions for CI

### ISSUE THREAD

**Issue by Warchant** [cpp-pm/hunter#40]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

Use github actions to integrate CI in this repo. 
The benefits of doing this:
1. path filters - CI will be triggered on changes to specific files/dirs, so push to PR-X triggers build for one package
2. all major OS are supported - mac, linux, windows
3. completely free for opensource repos
4. no need to maintain a separate repo with branch-per-project-ci

**Comment by bkotzz** [comment]
Agreed, we’ve been investigating GitHub actions and it looks good for our needs. We’ve signed up for the beta in this repo so we have the ability to start using it. Feel free to make some progress on this and put up PRs

**Comment by cristianadam** [comment]
I've mentioned on gitter, but I thought I should mention it here too:

> I've blogged about how to add GitHub Actions to a C++ project using CMake: https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/

**Comment by cristianadam** [comment]
I have a followup to the GitHub Actions blog article, https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/ 

Using ccache speeds up things considerably.

**Comment by rbsheth** [comment]
Done with #250
