### ISSUE TITLE
CURL Is broken

### ISSUE THREAD

**Issue by bazfp** [cpp-pm/hunter#404]
I'm not sure what's going on with the git actions but a CURL update was merged with a missing `find_package` and is currently broken.

https://github.com/cpp-pm/curl/pull/4

Need a new CURL update and merge ASAP.

**Comment by bazfp** [comment]
Anything that uses CURL will get the following at the moment:

```
  Target "x" links to target "intsizeof::intsizeof" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**Comment by rbsheth** [comment]
Should be fixed by https://github.com/cpp-pm/curl/pull/4

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.302
