### ISSUE TITLE
Problems with caching

### ISSUE THREAD

**Issue by drodin** [cpp-pm/hunter#421]
There is a general problem, which I'll try to illustrate with an example.

After recent altering of CMAKE_ARGS for 'opusfile' package https://github.com/cpp-pm/hunter/pull/415/commits/d061f8d740ae034e1366b73722c0bca14bd7a8fc

I have a problem with testing of 'SDL_mixer' package, which is dependent on 'opusfile' one
Tests are failing for all systems for which cache had been uploaded https://github.com/drodin/hunter/actions/runs/992722405
Sample of error: https://github.com/drodin/hunter/runs/2969916903?check_suite_focus=true#step:7:8164
```
-- [hunter *** DEBUG *** 2021-07-02T07:01:08] Package installed from cache: opusfile
...
  Imported target "opusfile::opusfile" includes non-existent path
```

Problem goes away if I disable cache server by adding *set(HUNTER_USE_CACHE_SERVERS NO)* to *examples/SDL_mixer/CMakeLists.txt* https://github.com/drodin/hunter/commit/1ad354345088578ade43adc4ebdd9e74a0a08045
Testing goes successful, as 'opusfile' package is built from source
https://github.com/drodin/hunter/actions/runs/992745793

**Comment by NeroBurner** [comment]
I haven't looked, but I suspect, that opsufile generates a non-relocatable `opusfile-config.cmake` file. This means some paths in the config file are absolute paths, which causes isses, because the cache-directory isn't the same on all the machines.

I propose to fix the opusfile package
