### ISSUE TITLE
Update protobuf to 3.10.0

### ISSUE THREAD

**Issue by hjmallon** [cpp-pm/hunter#46]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]

---

I would like to update Protobuf to the latest. It had a hunter-package version so that will need rebasing. Please could someone fork the old one with a branch pointing to https://github.com/protocolbuffers/protobuf/releases/tag/v3.10.0 and I will rebase the hunterization patches and test them.

**Comment by bkotzz** [comment]
I’ve created a fork of the hunter-packages repo in the cpp-pm org, and invited you to a GitHub group that gives you write access, so you should be able to push branches as needed and open PRs. Let me know if you need anything else

**Comment by hjmallon** [comment]
https://github.com/cpp-pm/hunter/pull/55
