### ISSUE TITLE
ffmpeg example build failed on ubuntu

### ISSUE THREAD

**Issue by zuowanbushiwo** [cpp-pm/hunter#464]
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://hunter.readthedocs.io/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://hunter.readthedocs.io/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **[No]**

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* <link-to-log-file>
[log.txt](https://github.com/cpp-pm/hunter/files/7074904/log.txt)

I'm using the next command line on generate step:
```
cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DCMAKE_BUILD_TYPE=Release
```

---

Thanks

**Comment by NeroBurner** [comment]
which hunter version did you try? Which HunterGate is checked out? Which Ubuntu Version are you running?

the following lines from your logs look fishy to me

```
-- [hunter *** DEBUG *** 2021-08-30T07:09:40] Secondary HunterGate (use old settings)
CMake Error at cmake/HunterGate.cmake:389 (include):
  include could not find load file:

    /home/packager/example/hunter/_Base/Download/Hunter/xxxxxxxxxx/xxxxxxx/Unpacked/cmake/Hunter
Call Stack (most recent call first):
  CMakeLists.txt:4 (HunterGate)
```

**Comment by zuowanbushiwo** [comment]
Hi   NeroBurner 
Thanks!  I now use another method.
