### ISSUE TITLE
New Package ittapi

### ISSUE THREAD

**Issue by craffael** [cpp-pm/hunter#480]
I'm planning to contribute [ittapi](https://github.com/intel/ittapi) as a package to hunter. But for this to work I need to patch the source's of ittapi. Can you create a repository `cpp-pm/ittapi` for me? (I'm basically following this [guide](https://hunter.readthedocs.io/en/latest/creating-new/patch.html))

**Comment by rbsheth** [comment]
https://github.com/cpp-pm/ittapi

**Comment by craffael** [comment]
Great Thanks!
