### ISSUE TITLE
New package tcmalloc

### ISSUE THREAD

**Issue by craffael** [cpp-pm/hunter#481]
I'm planning to contribute [tcmalloc](https://github.com/google/tcmalloc) as a package to hunter. But for this to work I need to add a CMake build system to tcmalloc. Can you create a repository `cpp-pm/tcmalloc` for me? (I'm basically following this [guide](https://hunter.readthedocs.io/en/latest/creating-new/patch.html))

**Comment by rbsheth** [comment]
https://github.com/cpp-pm/tcmalloc
