### ISSUE TITLE
Cryptopp compiles failed on Android.

### ISSUE THREAD

**Issue by olliwang** [cpp-pm/hunter#495]
The compile error is caused by failing to identify the `cpu-features.h` header. I submitted a PR to fix this long time ago but no response. Can someone take a look at it? Thanks. https://github.com/cpp-pm/cryptopp/pull/1

**Comment by olliwang** [comment]
Thanks for merging the https://github.com/cpp-pm/cryptopp/pull/1 fix. I made a PR for hunter to adopt this fix  https://github.com/cpp-pm/hunter/pull/496

**Comment by rbsheth** [comment]
@olliwang Does it work now?

**Comment by olliwang** [comment]
> @olliwang Does it work now?

Yes, I just tested on the latest release. Thanks for merging! :)
