### ISSUE TITLE
pcre source link is out of date

### ISSUE THREAD

**Issue by tstack** [cpp-pm/hunter#540]
The link to the pcre source tar ball is out of date:

https://github.com/cpp-pm/hunter/blob/132dc3c571e41764da09c8752ac590aaf2e9bf10/cmake/projects/libpcre/hunter.cmake#L19

The "ftp.pcre.org" site has been decommissioned, looks like it was moved to sourceforge -- https://sourceforge.net/projects/pcre/files/pcre/8.41/

**Comment by rbsheth** [comment]
@tstack thanks for the report. Are you able to submit a PR to fix?

**Comment by NeroBurner** [comment]
fixed with #575
