### ISSUE TITLE
Update "asio" package to 1.22.1

### ISSUE THREAD

**Issue by Tradias** [cpp-pm/hunter#563]
Hunterized repo: https://github.com/cpp-pm/asio

Should be a simple matter of pulling upstream, since the build requirements of asio did not change.

**Comment by NeroBurner** [comment]
If you want we'll add you to the group to pushing those upstream changes to the asio package. Afterwards you can do a PR here to update to the latest tag.

**Comment by Tradias** [comment]
In that case I might as well create a PR to cpp-pm/asio first: https://github.com/cpp-pm/asio/pull/6

**Comment by rbsheth** [comment]
Closed by #564
