### ISSUE TITLE
Upgrade spdlog to 1.4.2

### ISSUE THREAD

**Issue by natanielcz** [cpp-pm/hunter#57]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

**Comment by bkotzz** [comment]
Are you looking to contribute? Are you looking for help? Etc

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.227
