### ISSUE TITLE
grpc not working using example

### ISSUE THREAD

**Issue by glencjones** [cpp-pm/hunter#572]
build grpc example
git clone  https://github.com/cpp-pm/hunter.git    #  at f4de16c2 
cd hunter
git submodule update --init 

cd to example grpc
mkdir build
cd build
cmake ...

last bit or error displayed
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/thread_manager/thread_manager.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/byte_buffer_cc.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/status.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/string_ref.cc.o
[ 99%] Building CXX object CMakeFiles/grpc++.dir/src/cpp/util/time_cc.cc.o
[ 99%] Linking CXX static library libgrpc++.a
[ 99%] Built target grpc++
gmake[3]: *** [Makefile:136: all] Error 2
gmake[2]: *** [CMakeFiles/gRPC-Release.dir/build.make:86: gRPC-Release-prefix/src/gRPC-Release-stamp/gRPC-Release-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/gRPC-Release.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/xxxxx/src/github/hunter_diff/hunter_base/_Base/xxxxxxx/7cc2fc6/56909bc/Build/gRPC
[hunter ** FATAL ERROR **] [Directory:/home/xxxxx/src/github/hunter_diff/hunter_base/cmake/projects/gRPC]

------------------------------ ERROR -----------------------------
    https://hunter.readthedocs.io/en/latest/reference/errors/error.external.build.failed.html
------------------------------------------------------------------

CMake Error at /home/xxxxxx/src/github/hunter_diff/hunter_base/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  /home/xxxxxx/src/github/hunter_diff/hunter_base/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
  /home/xxxxxx/src/github/hunter_diff/hunter_base/cmake/modules/hunter_download.cmake:623 (hunter_fatal_error)
  /home/xxxxx/src/github/hunter_diff/hunter_base/cmake/projects/gRPC/hunter.cmake:79 (hunter_download)
  /home/xxxxxxx/src/github/hunter_diff/hunter_base/cmake/modules/hunter_add_package.cmake:62 (include)
  CMakeLists.txt:8 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/home/xxxxxxx/src/github/hunter_diff/hunter_base/examples/gRPC/build/CMakeFiles/CMakeOutput.log".

**Comment by NeroBurner** [comment]
can reproduce locally. The relevant error is the following:

```
[ 94%] Building CXX object CMakeFiles/grpc++.dir/src/core/ext/transport/binder/transport/binder_transport.cc.o
/usr/bin/ld: /home/nero/repos/hunter/hunter/_Base/xxxxxxx/f845a29/56909bc/Install/lib/libre2.a(re2.cc.o): relocation R_X86_64_TPOFF32 against symbol `_ZN3re25hooks7contextE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/nero/repos/hunter/hunter/_Base/xxxxxxx/f845a29/56909bc/Install/lib/libabsl_random_internal_pool_urbg.a(pool_urbg.cc.o): relocation R_X86_64_TPOFF32 against `_ZZN4absl12lts_2021110215random_internal12_GLOBAL__N_19GetPoolIDEvE10my_pool_id' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/nero/repos/hunter/hunter/_Base/xxxxxxx/f845a29/56909bc/Install/lib/libabsl_cordz_functions.a(cordz_functions.cc.o): relocation R_X86_64_TPOFF32 against symbol `_ZN4absl12lts_2021110213cord_internal17cordz_next_sampleE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/nero/repos/hunter/hunter/_Base/xxxxxxx/f845a29/56909bc/Install/lib/libabsl_base.a(sysinfo.cc.o): relocation R_X86_64_TPOFF32 against `_ZGVZN4absl12lts_2021110213base_internal12GetCachedTIDEvE9thread_id' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/grpc_csharp_ext.dir/build.make:150: libgrpc_csharp_ext.so.22.0.0] Error 1
make[4]: *** [CMakeFiles/Makefile2:323: CMakeFiles/grpc_csharp_ext.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
```
I got it to work with providing a cmake-toolchain file which sets the `-fPIC` compile commands for all hunter dependencies

In the example directory `examples/gRPC` execute the following
```sh
cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../polly/gcc-pic.cmake
```

**Comment by glencjones** [comment]
Thanks..

fixed it using your idea, and added this into the build file

set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/fpic.cmake)

as I'll probably forget the above later in the week
