### ISSUE TITLE
Update"ceres-solver" package to 2.1

### ISSUE THREAD

**Issue by higordearaujo-bsy** [cpp-pm/hunter#619]
* I'm interested in an updated version of the package `ceres-solver`
* Here is the official site of package https://github.com/ceres-solver/ceres-solver
* Here's the huntereized version of the package https://github.com/hunter-packages/ceres-solver

* This package is using Git https://github.com/ceres-solver/ceres-solver.git

* Official GitHub repository: https://github.com/ceres-solver/ceres-solver
* Hunterized mirror: https://github.com/hunter-packages/ceres-solver

* Used build system: CMake

* [CMake](http://www.cmake.org/) 3.10 or later required.
* [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) 3.3+ (available in Hunter https://github.com/hunter-packages/eigen)
* [glog](https://github.com/google/glog) 0.3.5+. Recommended (available in Hunter https://github.com/hunter-packages/glog)
* [gflags](https://github.com/gflags/gflags). Needed to build examples and tests and usually a dependency for glog (available in Hunter https://github.com/hunter-packages/gflags).
* [SuiteSparse](http://faculty.cse.tamu.edu/davis/suitesparse.html) 4.5.6 or later. Needed for solving large sparse linear systems. Optional; strongly recommended for large scale bundle adjustment (available in hunter https://github.com/hunter-packages/suitesparse-metis-for-windows/)
* [Apple’s Accelerate sparse solvers](https://developer.apple.com/documentation/accelerate/sparse_solvers). As of Xcode 9.0, Apple’s Accelerate framework includes support for solving sparse linear systems across macOS, iOS et al. Optional (not available in Hunter)
* [Intel MKL](https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-mkl-for-dpcpp/top.html) (outdated version available in Hunter https://hunter.readthedocs.io/en/latest/packages/pkg/LAPACK.html) OR [ATLAS](http://math-atlas.sourceforge.net/) (not available in Hunter) OR [OpenBLAS](https://github.com/xianyi/OpenBLAS) (available in hunter https://github.com/hunter-packages/OpenBLAS) OR [LAPACK For Windows](http://icl.cs.utk.edu/lapack-for-windows/lapack/) (available in Hunter: https://github.com/hunter-packages/lapack). Required if SuiteSparse is enabled, Optional otherwise.
* [CUDA](https://developer.nvidia.com/cuda-toolkit) Optional (not available in Hunter)

--

Hunter provides version 2.0 at the moment, which does not support manifolds or CUDA. The dependency on CXSparse has been dropped in favor of builtin Eigen features.

**Comment by NeroBurner** [comment]
fixed with: https://github.com/cpp-pm/hunter/pull/703 providing ceres-solver 2.2.0

Released: https://github.com/cpp-pm/hunter/releases/tag/v0.25.2
