### ISSUE TITLE
Unexpected CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE: 'ARM64'

### ISSUE THREAD

**Issue by ccmvn** [cpp-pm/hunter#651]
Could you add an option to select x64 on Windows 11 ARM instead of ARM64?

> [hunter ** INTERNAL **] Unexpected CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE: 'ARM64'

**Comment by NeroBurner** [comment]
Which packages, what are your PC specs. Steps to reproduce. Please provide more information.

**Comment by ccmvn** [comment]
I use Windows 11 ARM64, but I have selected x64 as toolset in CMake

[hunter] Initializing Hunter workspace (a3d7f4372b1dcd52faa6ff4a3bd5358e1d0e5efd)
[hunter]   https://github.com/cpp-pm/hunter/archive/v0.24.0.tar.gz
[hunter]   -> C:/.hunter/_Base/Download/Hunter/0.24.0/a3d7f43
[hunter] Calculating Toolchain-SHA1
[hunter] Calculating Config-SHA1
[hunter] HUNTER_ROOT: C:/.hunter
[hunter] [ Hunter-ID: a3d7f43 | Toolchain-ID: 7224681 | Config-ID: c0769d7 ]

[hunter ** INTERNAL **] Unexpected CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE: 'ARM64'
[hunter ** INTERNAL **] [Directory:C:/Users/ccmvn/Desktop/Test]

------------------------------ ERROR -----------------------------
    https://hunter.readthedocs.io/en/latest/reference/errors/error.internal.html
------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.24.0/a3d7f43/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.24.0/a3d7f43/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_error_page)
  C:/.hunter/_Base/Download/Hunter/0.24.0/a3d7f43/Unpacked/cmake/modules/hunter_setup_msvc.cmake:141 (hunter_internal_error)
  C:/.hunter/_Base/Download/Hunter/0.24.0/a3d7f43/Unpacked/cmake/modules/hunter_finalize.cmake:117 (hunter_setup_msvc)
  C:/.hunter/_Base/Download/Hunter/0.24.0/a3d7f43/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
  CMakeLists.txt:49 (hunter_add_package)


Configuring incomplete, errors occurred!

**Comment by ccmvn** [comment]
LINE49: hunter_add_package(Boost COMPONENTS program_options filesystem)
LINE50: hunter_add_package(Microsoft.GSL)

**Comment by NeroBurner** [comment]
the error seems to come from here: https://github.com/cpp-pm/hunter/blob/132dc3c571e41764da09c8752ac590aaf2e9bf10/cmake/modules/hunter_setup_msvc.cmake#L137

It seems like there is no special handling for a MSVC ARM64 host toolchain yet.

**Comment by ccmvn** [comment]
Any update yet?

**Comment by ccmvn** [comment]
I opened a pull request and provided a fix: https://github.com/cpp-pm/hunter/pull/655
