### ISSUE TITLE
missing SHA1 details in v0.24.16 release note

### ISSUE THREAD

**Issue by mean-ui-thread** [cpp-pm/hunter#671]
the latest release notes for v0.24.16 is missing the SHA1 details.

https://github.com/cpp-pm/hunter/releases/tag/v0.24.16

I calculated it for you:

```
HunterGate(
    URL "https://github.com/cpp-pm/hunter/archive/v0.24.16.tar.gz"
    SHA1 "09668c254f01afeca1b3d3d2e4692ed5e0e39dcc"
)
```

You're welcome!

**Comment by NeroBurner** [comment]
Thanks! I've updated the release :+1:
