### ISSUE TITLE
unittest hunter_setup_msvc fails because of ARM64 change

### ISSUE THREAD

**Issue by NeroBurner** [cpp-pm/hunter#679]
Since https://github.com/cpp-pm/hunter/pull/655/files the target architecture (variable `HUNTER_MSVC_ARCH_TARGET`) for arm64 changed from `arm64` to `ARM64`, which broke the unittest `hunter_setup_msvc/CMakeLists.txt` because of the different capitalization

The architecture according to the `vcvarsall.bat /help` should be lower case, and some custom schemes (like `url_sha1_boost_library.cmake.in`) checks case sensitive for `arm64`. So those broke since the earlier mentioned PR

For reference the `vcvarsall.bat /help` output for `Visual Studio 17 2022` build-tools

```
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build>vcvarsall.bat /help
Syntax:
    vcvarsall.bat [arch] [platform_type] [winsdk_version] [-vcvars_ver=vc_version] [-vcvars_spectre_libs=spectre_mode]
where :
    [arch]: x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm | amd64_arm64
    [platform_type]: {empty} | store | uwp
    [winsdk_version] : full Windows 10 SDK number (e.g. 10.0.10240.0) or "8.1" to use the Windows 8.1 SDK.
    [vc_version] : {none} for latest installed VC++ compiler toolset |
                   "14.0" for VC++ 2015 Compiler Toolset |
                   "14.xx" for the latest 14.xx.yyyyy toolset installed (e.g. "14.11") |
                   "14.xx.yyyyy" for a specific full version number (e.g. "14.11.25503")
    [spectre_mode] : {none} for libraries without spectre mitigations |
                     "spectre" for libraries with spectre mitigations

The store parameter sets environment variables to support Universal Windows Platform application
development and is an alias for 'uwp'.

For example:
    vcvarsall.bat x86_amd64
    vcvarsall.bat x86_amd64 10.0.10240.0
    vcvarsall.bat x86_arm uwp 10.0.10240.0
    vcvarsall.bat x86_arm onecore 10.0.10240.0 -vcvars_ver=14.0
    vcvarsall.bat x64 8.1
    vcvarsall.bat x64 store 8.1

Please make sure either Visual Studio or C++ Build SKU is installed.
```

According to https://learn.microsoft.com/en-us/windows/arm/arm64ec-build#cmake-projects the cmake architecture to set for `ARM64EC` is `arm64ec`.

But to be sure we should ask someone to print the cmake `MSVC_CXX_ARCHITECTURE_ID` variable, on which the detection in `hunter_setup_msvc.cmake` is based on

Or maybe we just add a `STRING(TOLOWER)` and compare against lower case variables. This would match the lower case `vcvarsall.bat <arch>` argument

---

@ccmvn could you help out with the `MSVC_CXX_ARCHITECTURE_ID` printing for `amd64` and `arm64` hosts?

---

edit: fix `ARM64CE` -> `ARM64EC`

**Comment by NeroBurner** [comment]
@ccmvn could you also run `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build>vcvarsall.bat /help` to maybe get the right `arm64ce` architecture argument

**Comment by ccmvn** [comment]
> @ccmvn could you also run `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build>vcvarsall.bat /help` to maybe get the right `arm64ce` architecture argument

C:\Users\Admin>"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsamd64_arm64.bat" /help
Syntax:
    vcvarsall.bat [arch] [platform_type] [winsdk_version] [-vcvars_ver=vc_version] [-vcvars_spectre_libs=spectre_mode]
where :
    [arch]: x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm | amd64_arm64
    [platform_type]: {empty} | store | uwp
    [winsdk_version] : full Windows 10 SDK number (e.g. 10.0.10240.0) or "8.1" to use the Windows 8.1 SDK.
    [vc_version] : {none} for latest installed VC++ compiler toolset |
                   "14.0" for VC++ 2015 Compiler Toolset |
                   "14.xx" for the latest 14.xx.yyyyy toolset installed (e.g. "14.11") |
                   "14.xx.yyyyy" for a specific full version number (e.g. "14.11.25503")
    [spectre_mode] : {none} for libraries without spectre mitigations |
                     "spectre" for libraries with spectre mitigations

The store parameter sets environment variables to support Universal Windows Platform application
development and is an alias for 'uwp'.

For example:
    vcvarsall.bat x86_amd64
    vcvarsall.bat x86_amd64 10.0.10240.0
    vcvarsall.bat x86_arm uwp 10.0.10240.0
    vcvarsall.bat x86_arm onecore 10.0.10240.0 -vcvars_ver=14.0
    vcvarsall.bat x64 8.1
    vcvarsall.bat x64 store 8.1

Please make sure either Visual Studio or C++ Build SKU is installed.

C:\Users\Admin>

**Comment by NeroBurner** [comment]
so no change in the help message even though you installed the `ARM64CE` support

could you configure the following `CMakeLists.txt` file with the different target architectures? With the right `vsdevcmd.bat` calls beforehand

```
cmake -S . -B build -G "Visual Studio 17 2022" -A ARM64CE
cmake -S . -B build -G "Visual Studio 17 2022" -A ARM64
cmake -S . -B build -G "Visual Studio 17 2022" -A x64
cmake -S . -B build -G "Visual Studio 17 2022" -A x86
```

```cmake
cmake_minimum_required(VERSION 3.5)
project(PrintVar CXX)
message(STATUS "MSVC_CXX_ARCHITECTURE_ID: ${MSVC_CXX_ARCHITECTURE_ID}")
```

---

note: please use \`\`\` around the code to highlight them as code-blocks, something like the following

\`\`\`
some code you want to
highlight in a verbatim font
\`\`\`

**Comment by NeroBurner** [comment]
tested it for `x86`, `amd64` and `arm64`. I couldn't get `ARM64CE` to work (neither with vcvarsall.bat nor with a `cmake -A` flag).

`vcvarsall.bat` and `cmake -A` both don't care about capitalization. But their output has differing capitalization (or keywords)

All Tests ran on an Window 10 amd64 Host with MSVC Build Tools 2022

```
|-------------------|----------------------------|---------------|--------------------------|
| vcvarsall.bat     | vcvars initialized for msg | cmake -A      | MSVC_CXX_ARCHITECTURE_ID |
|-------------------|----------------------------|---------------|--------------------------|
| x86               | x86                        | WIN32         | X86                      |
|-------------------|----------------------------|---------------|--------------------------|
| amd64             | x64                        | x64           | x64                      |
| AMD64             | x64                        | x64           | x64                      |
| x64               | x64                        | x64           | x64                      |
| amd64             | x64                        | X64           | x64                      |
| amd64             | x64                        | amd64         | ERROR                    |
| amd64_amd64       | ERROR                      |               |                          |
|-------------------|----------------------------|---------------|--------------------------|
| amd64_arm64       | x64_arm64                  | ARM64         | ARM64                    |
| AMD64_ARM64       | x64_arm64                  | ARM64         | ARM64                    |
| amd64_arm64       | x64_arm64                  | arm64         | ARM64                    |
| arm64             | arm64                      | ARM64         | ARM64                    |
|-------------------|----------------------------|---------------|--------------------------|
| arm64ce           | ERROR                      |               |                          |
| arm64             | arm64                      | ARM64CE       | ERROR                    |
|-------------------|----------------------------|---------------|--------------------------|

```

a small `print_variables_x64.bat` looks as follows:
```cmd
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars32.bat" ^
  amd64
cmake -E rm -r -f build_x64
cmake -S . -B build_x64 -G "Visual Studio 17 2022" -A x64
pause
```

And then I just double click the `bat` file from the Explorer and get the wanted output

**Comment by ccmvn** [comment]
```The C compiler identification is MSVC 19.36.32532.0
The CXX compiler identification is MSVC 19.36.32532.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostarm64/arm64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostarm64/arm64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
MSVC_CXX_ARCHITECTURE_ID: ARM64EC
Configuring done```

**Comment by NeroBurner** [comment]
Ah thanks for the `ARM64EC` clarification. I updated the table above with the working combination

**Comment by NeroBurner** [comment]
I'll update the comparisons in `hunter_setup_msvc.cmake` of the input variables `MSVC_CXX_ARCHITECTURE_ID` and `CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE` to be case insensitive (using a `string(TOLOWER)` call before comparison).
And I'll use all lower case keywords for the set hunter variables `HUNTER_MSVC_ARCH`, `HUNTER_MSVC_ARCH_HOST` and `HUNTER_MSVC_ARCH_TARGET`.
Then the old toolchains compairing against `HUNTER_MSVC_ARCH==arm64` should work again and we will hopefully have less confusion in the future.

@ccmvn are you OK with those changes, or am I missing something important?

**Comment by ccmvn** [comment]
@NeroBurner These proposed changes seem to be logical and future-proof. Making the comparisons in hunter_setup_msvc.cmake case-insensitive for the input variables MSVC_CXX_ARCHITECTURE_ID and CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE is a wise move to prevent inconsistencies.

Also, the idea of using all lower case keywords for the HUNTER_MSVC_ARCH, HUNTER_MSVC_ARCH_HOST, and HUNTER_MSVC_ARCH_TARGET set hunter variables is a sound decision.

This should restore compatibility with older toolchains comparing against HUNTER_MSVC_ARCH==arm64 and hopefully reduce confusion in the future.

Just to add a bit here, when I first put this together, I was really just trying to get a quick fix in place because we needed it pronto. I didn't have much time to polish it up as much as I would have liked.

Unless there are specific concerns I might be overlooking, it seems like these changes are a solid step forward. @NeroBurner
