### ISSUE TITLE
Update "assimp" package

### ISSUE THREAD

**Issue by NukeBird** [cpp-pm/hunter#69]
https://github.com/assimp/assimp/releases/tag/v5.0.0 (2d2889f)

I think it's very important update:

> Implemented basic PBR materials into assimp.
> This adds the following texture types:
> BASE_COLOR
> NORMAL_CAMERA
> EMISSION_COLOR
> METALNESS
> DIFFUSE_ROUGHNESS

> Add support for importing GLTF2 animations.

**Comment by NukeBird** [comment]
actually I noticed just now that assimp uses hunter (but the ruslo ones, old version)
so update should be pretty straightforward

**Comment by rbsheth** [comment]
@NukeBird Want to try your hand at updating the package? Like you said, it should be very straightforward since I added Hunter support directly there. If you do, make sure to test your updated branch with CI (https://docs.hunter.sh/en/latest/creating-new/update.html#testing).
