### ISSUE TITLE
OpenCV force push access rights

### ISSUE THREAD

**Issue by NeroBurner** [cpp-pm/hunter#691]
@rbsheth I'm currently working on OpenCV 4.8.1 hunter package and I wrongly pushed the `hunter-4.8.1` branch. And I now can't remove the branch or force push updates.

Could you please elevate my permissions on the [OpenCV](https://github.com/cpp-pm/opencv) project

**Comment by rbsheth** [comment]
Fixed! See gitter for DM from me
