### ISSUE TITLE
Update sqlite3

### ISSUE THREAD

**Issue by kaihowl** [cpp-pm/hunter#70]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes(, but the link from the template is dead)**

---

I want to update sqlite to 3.30.1. I see that there is https://github.com/hunter-packages/sqlite3 with cmake additions. This repo has not been taken under the new cpp-pm umbrella as far as I can tell. Would this need to be migrated to the cpp-pm organization or should I create a new PR to the old repo for updating the code?

Moreover as there is an autotools scheme in hunter and sqlite is build using autotools AFAIK, I am wondering if I should attempt to switch this package to a different scheme and ditch the project fork repo for sqlite. I am not sure how to find and trace the original reasons for the fork.

**Comment by kaihowl** [comment]
Created #71 for the dead link in the templates.

**Comment by kaihowl** [comment]
I found part of the answer myself already
```
[hunter ** FATAL ERROR **] Autotools scheme not supported with Visual Studio
```
Source: https://ci.appveyor.com/project/kaihowl/hunter/builds/28946414/job/ju53it80g4oity5n

**Comment by rbsheth** [comment]
@kaihowl Created a new fork for you here https://github.com/cpp-pm/sqlite3 and added you to the package maintainers group.

**Comment by kaihowl** [comment]
Please check https://github.com/cpp-pm/sqlite3/pull/1. Even after joining the maintainers group, I do lack permissions to merge it myself. For "due process", it makes sense if someone else reviews the PR regardless.

**Comment by rbsheth** [comment]
@kaihowl Responded there, sorry for the delay.

**Comment by rbsheth** [comment]
@kaihowl PR there was reviewed, merged, and released. You should be able to make a hunter PR now.
