### ISSUE TITLE
Latest yaml-cpp version has an uppercase SHA1

### ISSUE THREAD

**Issue by cristianadam** [cpp-pm/hunter#72]
`yaml-cpp` package has in `hunter-v0.23.229.tar\hunter-0.23.229\cmake\projects\yaml-cpp\hunter.cmake` the following code:

```cmake
hunter_add_version(
  PACKAGE_NAME
  yaml-cpp
  VERSION
  "0.6.2-0f9a586-p1"
  URL
  "https://github.com/hunter-packages/yaml-cpp/archive/v0.6.2-0f9a586-p1.zip"
  SHA1
  956C2B5FBF5AA0EB8EF5EF890C0328B3AA357A13
  )
```
which works on Windows, but not that much on Linux.

The previous versions have lowercase SHA1s.

**Comment by rbsheth** [comment]
Should be fixed by https://github.com/cpp-pm/hunter/pull/73
