### ISSUE TITLE
Update curl to 8.5.0

### ISSUE THREAD

**Issue by hjmallon** [cpp-pm/hunter#734]
MR for the curl repo here https://github.com/cpp-pm/curl/pull/8
Then I will open an MR here

**Comment by NeroBurner** [comment]
Release for integration into hunter: https://github.com/cpp-pm/curl/releases/tag/v8.5.0-p0

**Comment by hjmallon** [comment]
https://github.com/cpp-pm/hunter/pull/738

**Comment by NeroBurner** [comment]
merged with https://github.com/cpp-pm/hunter/pull/738

**Comment by NeroBurner** [comment]
@hjmallon do you need a release to work with the new CURL?

**Comment by hjmallon** [comment]
I wouldn't say no :)

**Comment by NeroBurner** [comment]
Here you go :)
https://github.com/cpp-pm/hunter/releases/tag/v0.25.5
