### ISSUE TITLE
boost broken

### ISSUE THREAD

**Issue by usser0134** [cpp-pm/hunter#754]
Hey, boost package is broken since some time.. I wonder why nobody noticed.  Download link stored in hunter packages is broken since some time.. and cant donwload.. and few more issues with boost.  But main issue is that downlaod links are broken for archives

**Comment by hjmallon** [comment]
Which of the links here is broken? https://github.com/cpp-pm/hunter/blob/master/cmake/projects/Boost/hunter.cmake

1.83 works for me

**Comment by usser0134** [comment]
How i can chose another boost version?

**Comment by hjmallon** [comment]
You might need to update the version of hunter in use (see the releases on github) or you might have a hunter config file in your tree setting a specific version

**Comment by NeroBurner** [comment]
closing. please reopen if it happens with the latest Hunter version as well. If so reopen and update the issue description to mention the Boost and Hunter versions
