### ISSUE TITLE
cpp-pm/gate points to the original Hunter project

### ISSUE THREAD

**Issue by cristianadam** [cpp-pm/hunter#76]
https://github.com/cpp-pm/gate project's description points to the original Hunter project. It should be updated to `cpp-pm/hunter`.

**Comment by bkotzz** [comment]
Thanks for catching that - want to send a PR?

**Comment by cristianadam** [comment]
I don't think it's possible to make a PR with the description of the project changed.

I changed it in my fork, but if I create a PR I don't see the change.

**Comment by bkotzz** [comment]
Ahh yes I see what you mean now. Fixed
