### ISSUE TITLE
PROBLEM WITH hunter DOCUMENTATION

### ISSUE THREAD

**Issue by jayanthk82** [cpp-pm/hunter#762]
Hi, sir. This is jayanth. I am a college student passionate about doing something big in life. Still, I am stuck in my current situation and need clarification about finding the right career role. I found web3 technology, which excited me to work, but I needed someone around me to be passionate about working on web3 technology. Everyone around me was in the rat race to be placed in a software job, but I was not to be part of the rat race. So that's the reason I am writing this to you. If you connect with me, I can learn a lot from you about web3 technology and decentralized applications. And sorry for the unmatched title. Requesting you to connect with me by using issue section in  my python-dsa repo.

**Comment by NeroBurner** [comment]
closing, unrequested/unrelated attention grab/advertisement
