### ISSUE TITLE
Disable Hunter per default

### ISSUE THREAD

**Issue by NeroBurner** [cpp-pm/hunter#87]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

set the default for `HUNTER_ENABLED` to `OFF`

when using Hunter in a project I always disable it. When I open the project in my IDE (QtCreator, vscode) the first time the default cmake-configurations are used, which also includes Hunter. So even if I don't want to use Hunter I have to wait for Hunter to provide me with all dependencies, just to say no thank you afterwards

**Comment by Bjoe** [comment]
May I ask, why you are not add a `HUNTER_ENABLED` option with a default value `NO` in your project like I did
```
cmake_minimum_required(VERSION 3.2.0)

option(HUNTER_ENABLED "Enable Hunter package manager" NO)
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.co.............."
    SHA1 "....................."
    LOCAL
....
)

```


See https://github.com/pocoproject/poco/blob/f74be1d9e50a5d95c7758bb4bb89d888f54b4e52/CMakeLists.txt

**Comment by NeroBurner** [comment]
that's exactly what I did, and what (IMHO) every developer does when he/she shares a project with other developers. Why require every programmer to add the option override to all the projects?

**Comment by OvermindDL1** [comment]
Most of us prefer it to default to YES is why I would imagine.  ^.^

**Comment by bkotzz** [comment]
I’m not sure I understand the motive here. That flag mostly exists for projects that already have another way to download/build their dependencies (maybe they use a system package manager like apt get, maybe another c/c++ package manager like Conan, maybe they use submodules and build deps from source, etc). It’s useful when contributing to upstream projects, to convince them to support hunter without _needing_ hunter.

But there are also lots of projects that only use hunter, or use hunter by default, and this change would break their build until they set the option back on.

That’s a pretty invasive change. I’d only consider this if a fair amount of people are interested

**Comment by OvermindDL1** [comment]
> (maybe they use a system package manager like apt get, maybe another c/c++ package manager like Conan, maybe they use submodules and build deps from source, etc)

I never ever recommend that, that means that identical code isn't being compiled and used in all locations, you get non-reproducible builds and you lose a lot of LTO.

**Comment by bkotzz** [comment]
> > (maybe they use a system package manager like apt get, maybe another c/c++ package manager like Conan, maybe they use submodules and build deps from source, etc)
> 
> I never ever recommend that, that means that identical code isn't being compiled and used in all locations, you get non-reproducible builds and you lose a lot of LTO. A nice thing about hunter is it works with anything else as well.

Whether you, I or anyone else recommends it or not, lots projects do use those methods.  The hunter_enabled flag let’s hunter coexist with those methods in projects that don’t want to change for whatever reason.

**Comment by rbsheth** [comment]
Most usage of `HUNTER_ENABLED` is in third-party projects that do not use Hunter but accept our modifications to support their package. To default it to disabled is counter-intuitive behavior, especially for new users. You can always set the option in your project if you want it off. 😄
