### ISSUE TITLE
make Hunter silent by default

### ISSUE THREAD

**Issue by NeroBurner** [cpp-pm/hunter#88]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

set `HUNTER_STATUS_PRINT` by default to `OFF`

The Hunter messages are only interesting in the case of errors, otherwise they are just cluttering up the CI build jobs

**Comment by Bjoe** [comment]
The same like https://github.com/cpp-pm/hunter/issues/87#issuecomment-562103049 .... add a option in your project.

It will be confused new users when they see "nothing" at the very first time. It is not intuitive for new users in my opinion and btw. I found the output really helpful ... if somebody of my colleges have a problem local to buld, I always ask if the "hunter ID's" are the same as on our CI build, if not ... they lost ;-)

**Comment by rbsheth** [comment]
`HUNTER_STATUS_PRINT` can easily be toggled with an option. New users should definitely be seeing output.
