### ISSUE TITLE
I'd like to contribute zstd and asio

### ISSUE THREAD

**Issue by ned14** [cpp-pm/hunter#91]
I have a cmake hunterised fork of zstd at https://github.com/ned14/zstd, and a cmake hunterised fork of asio at https://github.com/ned14/asio

How do you guys want it contributed given that I assume hunter-packages is no longer open?

**Comment by NeroBurner** [comment]
could you try to bring you cmake specific changes upstream?

**Comment by ned14** [comment]
Chris won't allow it for ASIO.

For zstd, I can ask, and I shall.

**Comment by ned14** [comment]
https://github.com/facebook/zstd/issues/1922

**Comment by bkotzz** [comment]
FYI we do still fork packages if needed, it’s just done in the cpp-pm org. Let us know if you need one

**Comment by ned14** [comment]
You'll definitely need one for ASIO.

**Comment by rbsheth** [comment]
@ned14 New forks here:

https://github.com/cpp-pm/zstd
https://github.com/cpp-pm/asio

Added you to the packages team also. Please send your PRs against the hunter-* branches I made there.

**Comment by ned14** [comment]
I'm currently negotiating with the zstd maintainers for them to directly support hunter. So far it goes well.

I'll hopefully push ASIO later today. Thanks for your help.

**Comment by ned14** [comment]
@rbsheth Sorry, you've used the wrong base for the hunter-* branch. It ought to be https://github.com/cpp-pm/asio/releases/tag/asio-1-12-2 which is the latest stable release. Can you redo the branch against that release tag please?

Also, with old cmake hunter, the branch names in the packages directory were named after the release e.g. v0.5-p0. Has the policy on this changed? If so, should I ignore the branch naming conventions specified by https://docs.hunter.sh/en/latest/creating-new/create/cmake.html?

**Comment by ned14** [comment]
hunterisation zstd PR has been submitted to https://github.com/facebook/zstd/pull/1924

Can hunter directly use repos without a CMakeLists.txt in their base directory? It would be a shame to have to fork zstd purely and exclusively just to stick a dummy CMakeLists.txt in its root.

**Comment by NeroBurner** [comment]
We could try to add that functionality to hunter

Something like the subdirectory feature for git repos

https://github.com/ruslo/hunter/pull/928

**Comment by rbsheth** [comment]
@ned14 Fixed: https://github.com/cpp-pm/asio

I think the branches were just the version and the releases had the `-pX` suffixes.

**Comment by NeroBurner** [comment]
@ned14 for zstd you can use `hunter_source_subdir()` when the PR is merged

https://github.com/cpp-pm/hunter/pull/95

**Comment by ned14** [comment]
zstd accepted the PR, so it's ready to go. I've subscribed to PR #95 so I'll see when it's ready. Meanwhile I should be able to PR ASIO soon.

**Comment by rbsheth** [comment]
@ned14 #95 was merged and released in https://github.com/cpp-pm/hunter/releases/tag/v0.23.236, looking forward to your PRs!

**Comment by ned14** [comment]
I've got an ASIO PR ready, just was awaiting the SHA. I should push it soon.

**Comment by ned14** [comment]
What's the point of hunter-testing when PRs against hunter are CI checked?

Also the advice to use Appveyor doesn't work, due to lack of an appveyor.yml file in the root of hunter. I don't know why you don't have one of those.

**Comment by NeroBurner** [comment]
PRs against hunter check the consistency of the hunter package declaration. They don't check if the packages themselves build successfully. The packages themselves are tested at hunter-testing

The process is documented here https://docs.hunter.sh/en/latest/creating-new/create/cmake.html

The cpp-pm guys are working on simplifying this process (see https://github.com/cpp-pm/hunter/issues/9 and https://github.com/cpp-pm/hunter/issues/28 for example). Input on this is highly appreciated

**Comment by ned14** [comment]
The current new package add process is quite confusing for the uninitiated, but I am making progress:

- https://travis-ci.org/ned14/hunter-testing
- https://ci.appveyor.com/project/ned14/hunter-testing

Is it okay to remove whole chunks of CI testing? Specifically, the mingw CI tests, ASIO doesn't officially support mingw, and there's a header only target for those folk in any case.

**Comment by NeroBurner** [comment]
> remove whole chunks of CI testing?

yes, just add a comment on why the chunk was commented out and add a link to a failing ci-job showing the error. For example: https://github.com/ingenue/hunter/blob/pkg.ceres-solver/appveyor.yml#L32

I'd recommend looking into why gcc and clang are failing. It looks like `pthreads` is missing, as it fails at the linking stage
https://travis-ci.org/ned14/hunter-testing/jobs/624616633#L1009
```
/home/travis/build/ned14/hunter-testing/_testing/Hunter/_Base/79224c5/239e635/f550390/Install/lib/libasio_shared.so: undefined reference to `pthread_create'
```

**Comment by ned14** [comment]
Already fixed in the PR at https://github.com/cpp-pm/asio/pull/3

**Comment by ned14** [comment]
Ok PR is opened for hunter-testing https://github.com/cpp-pm/hunter-testing/pull/20

I'm a bit confused now what happens next for https://github.com/cpp-pm/hunter/pull/101. Do I have to do anything, or does what I PRed to hunter-testing auto-migrate over to hunter?

**Comment by rbsheth** [comment]
@ned14 First, we merge this PR. Then, I update `pkg.template` with the latest master and cut a branch `pkg.asio`. Then, your testing PR is merged into that branch.

As such, you should update this PR with the `-p1` release.

**Comment by ned14** [comment]
> As such, you should update this PR #101 with the -p1 release.

Just to be clear, PR #101 should be updated with the -p1 release, but without the changes to travis and appveyor right? To be absolutely clear, everything in hunter-testing apart from those two files?

**Comment by rbsheth** [comment]
That's right! I know it is confusing, but that's how the system works right now.

**Comment by ned14** [comment]
-p1 is pushed to PR #101

**Comment by rbsheth** [comment]
@ned14 Thanks, couple comments on #101 and then I can merge

**Comment by rbsheth** [comment]
@ned14 #101 merged, released here: https://github.com/cpp-pm/hunter/releases/tag/v0.23.237

**Comment by ned14** [comment]
Given:

https://ci.appveyor.com/project/ned14/hunter-testing/builds/29599780/job/wkuw7nx1mdirnh25

... could someone have a look at https://github.com/ned14/hunter-testing/blob/pkg.zstd/cmake/projects/zstd/hunter.cmake and tell me what I'm doing wrong with the new source subdir facility?

**Comment by NeroBurner** [comment]
I'm sorry, I goofed up the example in the documentation

https://github.com/cpp-pm/hunter/pull/105

you need to have another include to `hunter_source_dir` and the use the command
```
hunter_source_dir(
    zstd
    SOURCE_SUBDIR
    "build/cmake")
````

**Comment by ned14** [comment]
I tried that:

https://github.com/ned14/hunter-testing/blob/pkg.zstd/cmake/projects/zstd/hunter.cmake

And https://ci.appveyor.com/project/ned14/hunter-testing/build/job/xvp6go8qdvnf5ve2 complains about no such include file.

**Comment by NeroBurner** [comment]
hunter_source_subdir()

Forgot the sub in subdir... need ti update my PR too

On December 17, 2019 6:53:32 PM GMT+01:00, Niall Douglas <notifications@github.com> wrote:
>I tried that:
>
>https://github.com/ned14/hunter-testing/blob/pkg.zstd/cmake/projects/zstd/hunter.cmake
>
>And
>https://ci.appveyor.com/project/ned14/hunter-testing/build/job/xvp6go8qdvnf5ve2
>complains about no such include file.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cpp-pm/hunter/issues/91#issuecomment-566675318

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ned14** [comment]
zstd just in time for Christmas!
