### ISSUE TITLE
Upgrade Qt (also fix)

### ISSUE THREAD

**Issue by barcharcraz** [cpp-pm/hunter#99]
Qt is currently at 5.11, which is no longer supported (and thus the download link hunter tries returns a 404). This needs to be fixed by pointing at the "archival" download location or updating Qt to a supported version.

**Comment by bkotzz** [comment]
Thanks for reporting this. Would you like to submit a PR?

**Comment by barcharcraz** [comment]
maybe, I'm still figuring out how hunter works. in particular w.r.t. patches and pristine sources.

**Comment by rbsheth** [comment]
@barcharcraz I think the existing URLs should be fixed now. Please make a PR if you'd like to upgrade the Qt version in Hunter!

**Comment by rbsheth** [comment]
Fix released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.238
